### ISSUE TITLE
Q() fatel error in Rstudio

### ISSUE THREAD

**Issue by msgoussi** [talgalili/installr#100]
Dear Sir,
As you wrote in
source("https://www.r-statistics.com/wp-content/uploads/2010/04/upgrading-R-on-windows.r.txt")
quit(save = "no") inside a user defined function  is not working inside Rstudio, but it works properly in R.
Please advise.
Thanks

**Comment by talgalili** [comment]
This code currently does not work well from RStudio, this is well known. I don't see a way to fix it in the near future.
