### ISSUE TITLE
Install.R 

### ISSUE THREAD

**Issue by msgoussi** [talgalili/installr#101]
Dear Sir,
R is running in local Driver D:/R/R-3.4.0

When I run **install.R(keep_install_file = TRUE, download_dir =  "E:\\R Project\\R Associated Programs")**
I get the following 
The file was downloaded successfully into:
 E:\R Project\R Associated Programs/R-3.4.1-win.exe 

Running the installer now...
'E:\R' is not recognized as an internal or external command,
operable program or batch file.
[1] FALSE
Warning messages:
1: running command 'C:\windows\system32\cmd.exe /c E:\R Project\R Associated Programs/R-3.4.1-win.exe' had status 1 
2: In shell(install_cmd, wait = wait, ...) :
  'E:\R Project\R Associated Programs/R-3.4.1-win.exe' execution failed with error code 1

Would you please advise.
Thanks 
Mohamed

**Comment by talgalili** [comment]
Odd.
Can you see the file in:
E:\R Project\R Associated Programs/R-3.4.1-win.exe
Can you run it?

**Comment by msgoussi** [comment]
Yes the file is there and If i double click, it will start installation.

**Comment by msgoussi** [comment]
Dear Mr. Tal,
I found out where the error comes from
Because of the space in the path (indicated by *)
E:\R *Project\R*Associated *Programs/R-3.4.1-win.exe

I faced this problem before when I am trying to copy/xcopy files using shell, I overcome of this problem using shQoute.
would you please try to fix this problem.
Thanks and have a nice day.

**Comment by talgalili** [comment]
Hi @msgoussi 
What is "shQoute"?

**Comment by msgoussi** [comment]
Please review this article
http://www.wikihow.com/Copy-Files-in-Command-Prompt

if you are copying files/folder in R using shell command
x <- paste0("copy", "C:\Users\My_Documents\filename",
"D:\backup\My_Documents")
shell(x)

if the location of the file has space , you need to add double quotation
x <- paste0("copy", shQoute("C:\Users\My Documents\filename"),
shQoute("D:\backup\My
Documents"))

**Comment by talgalili** [comment]
Any way you could offer a patch and send a PR?

**Comment by talgalili** [comment]
Not sure how to followup on this. Closing. 
Please re-open if you want to discuss this further.
