### ISSUE TITLE
copy.packages.between.libraries not working for Global library

### ISSUE THREAD

**Issue by verajosemanuel** [talgalili/installr#102]
I've created a new global library this way:

`installr::create.global.library("~/R/Global")`

Then tried to move all my files to new folder this way:

`installr::copy.packages.between.libraries(from = "~/R/R-3.4.1", to = "~/R/Global", ask =T)`

Only options are 3.4.1 and 3.4.0, so can't copy to new Global library.

Tried this way too:

`installr::copy.packages.between.libraries(from = "~/R/R-3.4.1", to = "~/R/Global", ask =F )`

But I get an error:

```
Error in file.copy(from = paths_of_packages_to_copy_from, to = to_library,  : 
  more 'from' files than 'to' files
```

**Comment by talgalili** [comment]
This function is not intended for such a use.
I suggest you to go through the steps here:
https://www.r-statistics.com/2011/04/how-to-upgrade-r-on-windows-7/

**Comment by verajosemanuel** [comment]
hi talgalili

The link you provided is not related to my issue. Maybe I'm wrong, but  in that case what for is intended copy.packages.between.libraries function?
