### ISSUE TITLE
Administrator issue

### ISSUE THREAD

**Issue by jinghuazhao** [talgalili/installr#106]
My colleague has indicated your package to me and I found it great.

Maybe I missed earlier post but I will outline our issue at work, where we have to install IT-approved version of R executable. We could get around this by asking IT to install the latest Windows executable to a dedicated directory and let your installr() point to it -- it looks possible when examining the software list from it.

If that is indeed possible, it could be a great help for us -- it should then allow for moving R packages under new version of R.

**Comment by talgalili** [comment]
Hi,
You may wish to use the function `install.URL()` to do what you want (I hope it would work on an internal network, I've never tried it).

**Comment by jinghuazhao** [comment]
Thanks Tal. In fact our IT already installed R, so it is only required put a link from desktop while probably manually move the R packages. Jing Hua
