### ISSUE TITLE
Worldmap package error, Error in grid.Call.graphics(C_polygon, x$x, x$y, index) : invalid color name 'blackcat'

### ISSUE THREAD

**Issue by ArtieLadie** [talgalili/installr#111]
Hello,

When I execute the code (end of this post)

Everything is fine, except when I try to execute

`wm`

I get

```
> wm
Error in grid.Call.graphics(C_polygon, x$x, x$y, index) : 
  invalid color name 'blackcat'
```
I am expecting worldmap instead.

Workaround is below .... please fix

```
wm$layers[[1]]$aes_params$colour <- "black"
wm
```

Code

```
install.packages(devtools)
library(devtools)
install_github("talgalili/installr", username="talgalili")
library(installr)
RStudio_CRAN_data_folder <- download_RStudio_CRAN_data(START = '2013-06-10',
                                                       END = '2013-06-17')
my_RStudio_CRAN_data <- read_RStudio_CRAN_data(RStudio_CRAN_data_folder)
wm <- pkgDNLs_worldmapcolor(pkg_name="timeROC",
                            dataset = my_RStudio_CRAN_data)
wm

```

**Comment by talgalili** [comment]
Thanks.
Could you send a patch in guthub? I'll review the code and accept.

**Comment by ArtieLadie** [comment]
Will do this at the earliest



-----Original Message-----

**Comment by talgalili** [comment]
10x :)



----------------Contact
Details:-------------------------------------------------------
Tal Galili, Ph.D. in Statistics

Tal.Galili@gmail.com

www.r-statistics.com (English)
www.biostatistics.co.il (Hebrew)  | www.talgalili.com (Hebrew)
----------------------------------------------------------------------------------------------

**Comment by talgalili** [comment]
I'm not available to add this at the time.
Please re-open if you want to discuss this further.
If someone wants to send a PR - I'll gladly review.
