### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by mareichhoff** [talgalili/installr#112]
Hello,

when I use either the CRAN or the development version of your package, I receive error messages and don't understand why:

```
R> installr::check.for.updates.R(page_with_download_url="https://cran.stat.unipd.it/bin/windows/base/", GUI=FALSE, notify_user=FALSE)
Error in if (there_is_a_newer_version) { : 
  missing value where TRUE/FALSE needed
```

even install::check.for.updates.R() leads to this error message.

Thank you very much for your hrelp!

Best regards,
Markus

**Comment by talgalili** [comment]
Not sure how to followup on this. Closing. 
Please re-open if you want to discuss this further.
