### ISSUE TITLE
read.xls

### ISSUE THREAD

**Issue by algorithmy** [talgalili/installr#113]
i'm new user on R, i'm trying to use read.xls function, I installed "installr" package, "gdata" package, and "perl"
but still have the same error
[could not find function "read.xls"]

**Comment by talgalili** [comment]
These functions are very old. Please use the readxl package instead:
https://cran.r-project.org/web/packages/readxl/index.html

**Comment by algorithmy** [comment]
Thanks Tal,

I fixed the issue, but thanks so much and I will try your solution as well.

best regards

Hesham

________________________________

**Comment by talgalili** [comment]
Not sure how to followup on this. Closing. 
Please re-open if you want to discuss this further.
