### ISSUE TITLE
install.r error:execution failed with error code 127

### ISSUE THREAD

**Issue by WeiCSong** [talgalili/installr#114]
Hi  Mr. Tal
i tried to update R using:

    

`install.R(keep_install_file=TRUE)`

but i got:

> >

The file was downloaded successfully into:
 C:\Users\goubegou\AppData\Local\Temp\Rtmp8wqvhS/R-3.5.1-win.exe 

>Running the installer now...

>[1] FALSE

>Warning messages:

>1: running command ' /c C:\Users\goubegou\AppData\Local\Temp\Rtmp8wqvhS/R-3.5.1-win.exe'had status 127 

>2: In shell(install_cmd, wait = wait, ...) :
  'C:\Users\goubegou\AppData\Local\Temp\Rtmp8wqvhS/R-3.5.1-win.exe' execution failed with error code 127

I can find and run C:\Users\goubegou\AppData\Local\Temp\Rtmp8wqvhS/R-3.5.1-win.exe in my computer,but installr seems unable to do so.Can anybody tell me how to deal with the error?Thanks!

**Comment by talgalili** [comment]
Try running R as admin, and then try running the command again.
