### ISSUE TITLE
In updateR, ask to copy Renviron.site

### ISSUE THREAD

**Issue by logworthy** [talgalili/installr#117]
Currently updateR asks if the user wants to copy Rprofile.site.  It would make sense to also ask about Renviron.site at the same time, either as a second question or combined.

**Comment by talgalili** [comment]
Sounds good. Would you be interested in updating the code for it and send a
patch?

**Comment by logworthy** [comment]
Sure, I can do that.  Would you prefer it combined into one prompt for the
user, or split out as two separate prompts?  And what tests would you like
me to run?

**Comment by logworthy** [comment]
Implemented in #140
