### ISSUE TITLE
Error in system(update_packages_expression...

### ISSUE THREAD

**Issue by zeblau** [talgalili/installr#119]
Hello!

I copied packages from old to new version of R, all went well. Next step, updating all packages, results in error. I assume it's a space in the directory path:

Error: '//server/username/My' not found'

**Comment by talgalili** [comment]
odd, what's your sessionInfo() ?

**Comment by zeblau** [comment]
R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 16299)

Matrix products: default
Locale:
[1] LC_COLLATE=Swedish_Sweden.1252
[2] LC_MONETARY=Swedish_Sweden.1252 LC_NUMERIC=C
[3] LC_TIME=Swedish_Sweden.1252

loaded via a namespace (and not attached):
[1] compiler_3.4.1

**Comment by talgalili** [comment]
>
> I cannot reproduce.
>
Please just run update.packages in the new R install manually.



>

**Comment by zeblau** [comment]
Can it be related to that I install to a server home directory?  Now that I try again with updateR(TRUE), it gives an error that UNC paths are not supported.

**Comment by talgalili** [comment]
Not sure how to followup on this. Closing. 
Please re-open if you want to discuss this further.
