### ISSUE TITLE
Error in install package 'stringr'

### ISSUE THREAD

**Issue by zachhuang4026** [talgalili/installr#122]
Hi talgalili, 
I got some issue during updating R version to 3.5.2.

> require(installr)
Loading required package: installr
Loading required package: stringr

Welcome to installr version 0.21.0

More information is available on the installr project website:
https://github.com/talgalili/installr/

Contact: <tal.galili@gmail.com>
Suggestions and bug-reports can be submitted at: https://github.com/talgalili/installr/issues

			To suppress this message use:
			suppressPackageStartupMessages(library(installr))

Warning message:
package ‘stringr’ was built under R version 3.5.2

**Comment by talgalili** [comment]
The text "package ‘stringr’ was built under R version 3.5.2"
is not something to be concerned about (you can run update.packages() if you want to fix it)
