### ISSUE TITLE
utils:download needs extra argument for Windows #120

### ISSUE THREAD

**Issue by chasemc** [talgalili/installr#125]
see: https://github.com/ficonsulting/RInno/issues/118#issuecomment-462050938

https://github.com/talgalili/installr/blob/56c51a8350ed7cfba2b52868db1dee0fb0bc17bd/R/install.inno.R#L52

**Comment by talgalili** [comment]
Hi @chasemc,
I see.
Can you please send a PR for this change:
https://github.com/talgalili/installr/blob/master/R/install.inno.R#L52

Once done, I'll review and approve.

Thanks :)

**Comment by chasemc** [comment]
Thanks @talgalili,

I didn't have the issue, so I can't say whether it is fixed.
@fdaugs or @RicPorteousNSWIS  can you try again after installing installr again using devtools (see below):

```
devtools::install_github("talgalili/installr@61e4a4f")
```

**Comment by chasemc** [comment]
Seems to work 👍

**Comment by talgalili** [comment]
Great, thanks. I'll close this task and will send it up to CRAN.
