### ISSUE TITLE
install.URL / install.packages.zip has issues with urls with parameters

### ISSUE THREAD

**Issue by RLogik** [talgalili/installr#126]
The method is a bit sloppily written and saves a downloaded file with a name that derives from the URL. This is hugely problematic when it comes to URLs containing parameters. My method `install.from.url` in the package [`rbettersyntax`](https://github.com/RLogik/rbettersyntax) avoids this issue, by cleanly assigning random names. It allows one to unzip files when necessary and flexibly determines where the package root folder lies. Here is an example:

`install.from.url(url='http://mydomain.de/R/repositories?file=mypackage.zip&v=1.3&lang=en', unzip=TRUE);`

By contrast, `installr::install.URL` / `installr::install.packages.zip`, cannot handle URLs like this, which are quite common.

**Comment by talgalili** [comment]
Hi RLogik,
Thanks for the input.
You're welcome to propose a pull request to make use of your method. I'm
just wondering if there are "interesting" software packages that would
require this feature.

Tal

**Comment by RLogik** [comment]
Hi @talgalili, first and foremost it really is down to the **principle of things*. You use something like `file.name.from.url(zip_url)`. This function needs to be rewritten as typically across various systems (Windows, Mac) *safe* file names must just consist of characters from

`a, b, …, z, A, B, …, Z, 0, 1, …, 9, -, _`

*etc*. Your auxiliary method absolutely needs to guarantee this, to not classify as sloppy. Alternatively, it needs really make strong guarantees on the assumption that the input (in your case the final segment of a URL) is always of this form. And it is common knowledge that most certainly is not the case for URLs in general.

So, since it is a temporary file, the logical thing to do is to just assign either a new random safe name, or something like `'tmp'`, `'tmp0'`, '`tmp1`', '`tmp2`', etc. whichever does not yet exists.

Secondly, yes there are such cases. Accessing files in some git repositories requires URLs which have parameters. Some objects are returned by querying an API: the objects are for very sensible reasons not permanently places in a URL structure, and one simply queries a single URL with multiple requests for various packages. I think Genomics might be like this, but they have their own `install.packages` method anyway.

**Comment by RLogik** [comment]
I would suggest two changes. Firstly an optional parameter (so as not to forcibly change the rest of your methods) to `file.name.from.url`:

```r
file.name.from.url <- function(URL, rm.params=FALSE) {
 #  tail(strsplit(URL,   "/")[[1]],1)
   # corrected to use R's base function thanks to Uwe's remark.
   name <- basename(URL);
   if(rm.params) name <- gsub('^((?:(?!\\?).)*).*', '\\1', name, perl=TRUE);
   return(name);
}
```
and secondly, an implementation of this method at least in `install.packages.zip`
```r
install.packages.zip <- function(zip_URL) {
   # zip_URL is the URL for the package_name.zip file
   zip_filename <- file.path(tempdir(), file.name.from.url(zip_URL, rm.params=TRUE)); ## <- changed
   # the name of the zip file MUST be as it was downloaded...
   # (2019.02.20) no it doesn't! R reads the DESCRIPTION file and determines the package name from this.
   download.file(zip_URL, destfile=zip_filename, mode = 'wb')   
   install.packages(pkgs= zip_filename, repos=NULL)   
   unlink(zip_filename)
   invisible(NULL)
}
```
and possibly in the same manner in `install.URL`. The coding assumption *the name of the zip file MUST be as it was downloaded* is wrong. You can name a downloaded file any old way. R installs packages using the information in the **DESCRIPTION** file, and not based on the folder name.

**Comment by talgalili** [comment]
Thanks for the detailed input. If you can get it to a working pull request that would be great, otherwise, I'll go over your propose code changes manually (it would take me some time to get to it this way, but I'll keep this issue open and will eventually get to it).

Thanks again, T

**Comment by talgalili** [comment]
Hey, could you please propose a pull request for me to review?

**Comment by RLogik** [comment]
Done! (Sorry, had a lot on my plate recently.)
