### ISSUE TITLE
install.Rtools() doesn't work

### ISSUE THREAD

**Issue by Nelson-Gon** [talgalili/installr#128]
Using `install.Rtools()` returns:

>Error: 'find_rtools' is not an exported object from 'namespace:devtools'
Indeed, this is not exported from devtools. What is the work around?

**Comment by talgalili** [comment]
The recent version on github should have this fixed.
Please check by running:
`remotes::install_github('talgalili/installr')`

If it doesn't work, please reopen this ticket.

Thanks :)
