### ISSUE TITLE
Error result after installr 0.21.3 was used

### ISSUE THREAD

**Issue by squeezer44** [talgalili/installr#130]
I want to update my local RStudio from Version 1.1.456 up to 1.2.1335.  
So I decided to use installr for doing so.  
After loading library(installr) I ran install.RStudio() and got the eror result below.  

I ask for help please to:  
1. understand why that happened  
2. avoid that error  
3. Update my local RStudio environment properly.  

**Thanks a lot!**

- Error result after installr is used

> Explanation of the error: You didn't enter a valid .EXE URL.   
This is likely to have happened because there was a change in the URL of the installer file in the download page of the software (making our function unable to know what to download).   
> 
> This might have already been fixed in the latest version of installr. Install the latest version of installr using devtools::install_github('talgalili/installr') and try again.  
> 
> If this doesn't help please e-mail: tal.galili@gmail.com and let me know this function needs updating/fixing (please include the output of sessionInfo() ) - thanks!  
> 
> We failed to download the file into:  
 C:\Users\CHRIST~1\AppData\Local\Temp\Rtmp0IO5S2/http:   
(i.e.: the installation failed)  

- Result of sessionInfo()  

> R version 3.5.1 (2018-07-02)  
Platform: x86_64-w64-mingw32/x64 (64-bit)  
Running under: Windows >= 8 x64 (build 9200)  
> 
> Matrix products: default
> 
> locale:  
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.1252    
> 
> attached base packages:  
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:  
[1] installr_0.21.3 stringr_1.4.0    
> 
> loaded via a namespace (and not attached):  
[1] compiler_3.5.1 magrittr_1.5   tools_3.5.1    yaml_2.2.0     stringi_1.4.3

**Comment by talgalili** [comment]
They probably changed their URL. I'll look into it and get back to you.

**Comment by squeezer44** [comment]
@talgalili 
WOW - extremely fast reponse :-)
Thx a lot!

**Comment by squeezer44** [comment]
@talgalili 
Sorry if I have to annoy you but did you have the chance to look at the problem?

**Comment by talgalili** [comment]
Hi Christian.
The recent version of installr on github solved this issue.

run:

devtools::install_github('talgalili/installr')

library(installr)

install.RStudio()

<https://github.com/talgalili/installr#usage>
Please check and confirm.

Cheers,
T

**Comment by squeezer44** [comment]
Hi @talgalili ,

Thank you very much. It went through very fast and without any probs.
Checked and confirmed.

Best,
Christian
