### ISSUE TITLE
Add progress bar and checklist during install.

### ISSUE THREAD

**Issue by Nelson-Gon** [talgalili/installr#131]
I just used `updateR()` with the latest version of `installr` at the time of writing. I did however notice that it was almost hard for me to know what was going on. For instance, I was met with the following that ended with:

`No packages to copy.  Goodbye :)`

I at that point assumed perhaps installation was done but it really wasn't and I could have easily quit without finishing the installation. 

My suggestion therefore is to have some sort of progress bar and a checklist that shows how many of the processes that need to be done have been completed. That way, a user in my opinion can have a better idea what steps are remaining.

Thank you.

**Comment by talgalili** [comment]
The installation of R is done externally to R, so I don't have a way to monitor it (that I know of). Sorry.
