### ISSUE TITLE
Error in installing ‘installr’

### ISSUE THREAD

**Issue by Manikgarg** [talgalili/installr#132]
Hi! 
Please find the code with error herewith.

`> install.packages('installr')`
`Installing package into ‘/pathToR/R/x86_64-redhat-linux-gnu-library/3.5’
(as ‘lib’ is unspecified)
Warning message:
package ‘installr’ is not available (for R version 3.5.1)`

I also tried to install the latest version from GitHub as suggested in https://www.rdocumentation.org/packages/installr/versions/0.21.3 and get the following error:

`> devtools::install_github('talgalili/installr')`
`Downloading GitHub repo talgalili/installr@master
✔  checking for file ‘/scratch/RtmpTYjh1Z/remotes6216e54ed72/talgalili-installr-8e76427/DESCRIPTION’ ...
─  preparing ‘installr’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Removed empty directory ‘installr/data’
─  building ‘installr_0.22.0.tar.gz’
   
Installing package into ‘/pathToR/R/x86_64-redhat-linux-gnu-library/3.5’
(as ‘lib’ is unspecified)
ERROR:  Windows-only package
* removing ‘/pathToR/R/x86_64-redhat-linux-gnu-library/3.5/installr’
Error: Failed to install 'installr' from GitHub:
  (converted from warning) installation of package ‘/scratch/RtmpTYjh1Z/file621298d9c93/installr_0.22.0.tar.gz’ had non-zero exit status`

**Comment by Manikgarg** [comment]
I see that I am trying to install it on a linux platform while the [documentation ](https://www.rdocumentation.org/packages/installr/versions/0.21.3) suggests that it is only for Windows OS. I think, it solves the issue. Is there a similar package for Linux users? Thanks!

**Comment by talgalili** [comment]
Indeed. Sadly not one that I know of (if you discover one, or write one,
please let me know in the comments so that I might propose to integrate it
with installr :) )

**Comment by Manikgarg** [comment]
Sure, thanks! :)
