### ISSUE TITLE
GraphicsMagick – unable to install

### ISSUE THREAD

**Issue by GegznaV** [talgalili/installr#133]
Error installing "GraphicsMagick" through GUI:
```r
installr::installr()
```

![image](https://user-images.githubusercontent.com/12725868/62447874-097dc100-b76f-11e9-9999-9eb833f552eb.png)

After pressing "OK" :
```r
Explanation of the error: You didn't enter a valid .EXE URL. 
This is likely to have happened because there was a change in the URL of the installer file in the download page of the software (making our function unable to know what to download). 

This might have already been fixed in the latest version of installr. Install the latest version of installr using devtools::install_github('talgalili/installr') and try again.

If this doesn't help please e-mail: tal.galili@gmail.com and let me know this function needs updating/fixing (please include the output of sessionInfo() ) - thanks!
```

```
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

other attached packages:
[1] installr_0.22.0
```

**Comment by talgalili** [comment]
I cannot reproduce this problem.
Can you please run:
install.ImageMagick()
And see if that works or not?

**Comment by GegznaV** [comment]
My question was about **GraphicsMagick**, (not "Image" one), just i didn't notice, that in the figure muse pointed to the wrong field (now I corrected it). `installr::install.graphicsmagick()` still does not work.

**Comment by GegznaV** [comment]
Unfortunately, I cannot reopen the issue.

**Comment by talgalili** [comment]
ok, version 0.22.1 on github now partially fixes this.
