### ISSUE TITLE
Add Appveyor integration

### ISSUE THREAD

**Issue by russHyde** [talgalili/installr#137]
**Is your feature request related to a problem? Please describe.**
There are currently no automated tests in `installr`.

I am trying to fix a bug with `create.global.library` (https://github.com/talgalili/installr/pull/136) and have introduced some testthat tests; these tests are skipped during CI on Travis because installr is pinned to Windows (by OS_type: windows in the DESCRIPTION) and Travis is an Ubuntu-based system. 

As such I'd like to add appveyor integration so that any tests can be ran (on a windows setup) whenever anyone pushes to installr on github.

**Describe the solution you'd like**
I would like to add appveyor integration. This will require that @talgalili (or another maintainer) open an Appveyor account and link installr to that account (details here: https://bookdown.org/rdpeng/RProgDA/continuous-integration.html and here: https://github.com/krlmlr/r-appveyor/blob/master/README.md). Once that's done I'm happy to push a PR that adds appveyor integration.

**Describe alternatives you've considered**
I'm not aware of any other windows-based CI solutions for which there is good tools for R packages.

**Additional context**

**Comment by talgalili** [comment]
Thanks @russHyde 
I think I've now created the link properly, see here: https://ci.appveyor.com/project/talgalili/installr
Please confirm/create a PR. Once done, I'll be happy to accept it.

Tal
