### ISSUE TITLE
update R failed

### ISSUE THREAD

**Issue by philhpaul** [talgalili/installr#142]
Ran the r update according to screen shots provided on line. Trying to update 3.4.2 to current 3.6.2. Ended with: 
Running the installer now...
Installation status:  TRUE . Removing the file:
 C:\Users\phpau\AppData\Local\Temp\Rtmpq4AON7/R-3.6.2-win.exe 
 (In the future, you may keep the file by setting keep_install_file=TRUE)
Followed by many:
Error in readRDS(file) : 
  cannot read workspace version 3 written by R 3.6.0; need R 3.5.0 or newer.
Ending with:
No packages to copy.  Goodbye :) 
[1] TRUE
Warning message:
running command 'C:/PROGRA~1/R/R-3.6.2/bin/Rscript.exe -e " options .......
 
Rstudio has a fatal error on start-up. R3.6.2 has no installed packages. 

**To Reproduce**

Learn how to make a great R reproducible example in the following URL:
https://stackoverflow.com/a/5963610/256662

And please supply us with such information so that we will be able to help you with solving the issue.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by talgalili** [comment]
You probably have .Rdata file somewhere that you've saved with objects that
for some reason cannot be read by the new R version. You can open your old
R, erase all objects, and then try to open the new R.
It also makes me wonder if this should be a function done in updateR...

T

**Comment by talgalili** [comment]
Closing.
