### ISSUE TITLE
installr version 0.22.0 - stringr package 

### ISSUE THREAD

**Issue by kerrynsmith** [talgalili/installr#145]
**Describe the bug**
Trying to use "library(SNPRelate)" but apparently it's not available on R version 3.6.2. Attempted to upgrade R by using "installr" package, but it needs the package "stringr". When stringr is loaded i get a weird bug report message - below.

I have searched the stringr package and reloaded it more than once and it comes up as succesfully unpacked but also needs to be loaded based on the error message.

**To Reproduce**

library(installr)
Loading required package: stringr

Welcome to installr version 0.22.0

More information is available on the installr project website:
https://github.com/talgalili/installr/

Contact: <tal.galili@gmail.com>
Suggestions and bug-reports can be submitted at: https://github.com/talgalili/installr/issues

			To suppress this message use:
			suppressPackageStartupMessages(library(installr))

anyone know a way around this?

**Comment by talgalili** [comment]
Hey, I don't see a bug in what you wrote. Can you please add an error message?
