### ISSUE TITLE
Timeout when running installr::updateR()

### ISSUE THREAD

**Issue by kstierhoff** [talgalili/installr#146]
**Describe the bug**
installr::updateR() fails with the following message:
`Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") : InternetOpenUrl failed: 'The operation timed out'`

I am running R v3.6.2 on Windows.

**Comment by kstierhoff** [comment]
Interestingly, restarting my computer and trying again first thing using the R GUI worked fine. I should have tried this before submitting an issue. However, I'm not sure why it worked.

**Comment by talgalili** [comment]
Thanks for the report, and for closing it :)

T
