### ISSUE TITLE
install.rtools() failure w unclear error message

### ISSUE THREAD

**Issue by ajdamico** [talgalili/installr#158]
might be permissions but dunno..  basically new windows machine.  thanks

	C:\Users\AnthonyD>"c:\Program Files\r\R-4.0.2\bin\x64\Rterm.exe"

	R version 4.0.2 (2020-06-22) -- "Taking Off Again"
	Copyright (C) 2020 The R Foundation for Statistical Computing
	Platform: x86_64-w64-mingw32/x64 (64-bit)

	R is free software and comes with ABSOLUTELY NO WARRANTY.
	You are welcome to redistribute it under certain conditions.
	Type 'license()' or 'licence()' for distribution details.

	  Natural language support but running in an English locale

	R is a collaborative project with many contributors.
	Type 'contributors()' for more information and
	'citation()' on how to cite R or R packages in publications.

	Type 'demo()' for some demos, 'help()' for on-line help, or
	'help.start()' for an HTML browser interface to help.
	Type 'q()' to quit R.

	> install.packages("installr")
	Installing package into 'C:/Users/AnthonyD/Documents/R/win-library/4.0'
	(as 'lib' is unspecified)
	--- Please select a CRAN mirror for use in this session ---
	trying URL 'https://cloud.r-project.org/bin/windows/contrib/4.0/installr_0.22.0.zip'
	Content type 'application/zip' length 341603 bytes (333 KB)
	downloaded 333 KB

	package 'installr' successfully unpacked and MD5 sums checked

	The downloaded binary packages are in
			C:\Users\AnthonyD\AppData\Local\Temp\3\RtmpqMIK07\downloaded_packages
	> library(installr)
	Loading required package: stringr

	Welcome to installr version 0.22.0

	More information is available on the installr project website:
	https://github.com/talgalili/installr/

	Contact: <tal.galili@gmail.com>
	Suggestions and bug-reports can be submitted at: https://github.com/talgalili/installr/issues

							To suppress this message use:
							suppressPackageStartupMessages(library(installr))

	> install.rtools()
	Loading required namespace: pkgbuild
	Loading required package: htmltab
	No encoding supplied: defaulting to UTF-8.
	Argument 'which' was left unspecified. Choosing first table.
	Error: Couldn't find a table.
	>
	> traceback()
	9: stop(mess, call. = F)
	8: ifstop(cond = length(Node) == 0, mess = "Couldn't find a table.")
	7: select_tab.default(which = which, Node = Node)
	6: select_tab(which = which, Node = Node)
	5: check_type.character(doc = doc, which = which)
	4: check_type(doc = doc, which = which)
	3: htmltab::htmltab(page_with_download_url)
	2: install.Rtools(...)
	1: install.rtools()

**Comment by burgerga** [comment]
Should be solved by some recent changes to installr, can you retry after installing installr from github with `remotes::install_github('talgalili/installr')`?

**Comment by burgerga** [comment]
Should be solved
