### ISSUE TITLE
AccŠs refus

### ISSUE THREAD

**Issue by Siwarattia1234** [talgalili/installr#160]
**Describe the bug**
Installing the newest version of R,
 please wait for the installer file to be download and executed.
 Be sure to click 'next' as needed...
essai de l'URL 'https://cran.rstudio.com/bin/windows/base/R-4.0.4-win.exe'
Content type 'application/x-msdownload' length 88562280 bytes (84.5 MB)
downloaded 0 bytes

The file was downloaded successfully into:
 C:\Users\USER\AppData\Local\Temp\RtmpUnjmNG/R-4.0.4-win.exe 

Running the installer now...
AccŠs refus‚.

Installation status:  FALSE . Removing the file:
 C:\Users\USER\AppData\Local\Temp\RtmpUnjmNG/R-4.0.4-win.exe 
 (In the future, you may keep the file by setting keep_install_file=TRUE) 
[1] FALSE
Warning messages:
1: In download_fun(exe_URL, destfile = exe_filename, quiet = FALSE,  :
  downloaded length 0 != reported length 88562280
2: In shell(install_cmd, wait = wait, ...) :
  'C:\Users\USER\AppData\Local\Temp\RtmpUnjmNG/R-4.0.4-win.exe' execution failed with error code 1
>

**Comment by burgerga** [comment]
Are you running anti-virus? I believe this can sometimes happen when
antivirus wants to scan the file first, so you cannot open it yet.

Can you run it with `keep_install_file=TRUE` and if you get this error, try
to open it manually?

**Comment by talgalili** [comment]
No response - closing.
