### ISSUE TITLE
Install.rtools requires htmltab which is not currently available on CRAN

### ISSUE THREAD

**Issue by dturkenk** [talgalili/installr#161]
**Describe the bug**
When trying to use `install.rtools()` on a newly upgraded R 4.0.4 environment running on Windows, `installr` tries to load `htmltab`. `htmltab` was removed from CRAN on 1/21/2021 due to problems in the check. In order to build `htmltab` from source, we need `rtools` which leads to a circular dependency.

We were able to work around this by installing rtools directly rather than through `installr.`

It doesn't appear `htmltab` is currently maintained (https://github.com/crubba/htmltab/issues/23) so there might not be an alternative approach.

**To Reproduce**

Running on Windows 10 with a newly upgraded R 4.0.4 with no rtools. I'm unable to create an actual reprex or get full session info at this time, but I can create a new environment to reproduce if needed.

```
> installr::install.rtools()
Loading required package: htmltab
Loading required package: htmltab
Error in loadNamespace(name) : there is no package called 'htmltab'
In addition: Warning messages:
1: package 'htmltab' is not available for this version of R
A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages 
2: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called 'htmltab'

> install.packages("htmltab")
WARNING: Rtools is required to build R packages but no version of Rtools compatible with the currently running version of R was found. Note that the following incompatible version(s) of Rtools were found:
  - Rtools 3.5 (installed at C:\Users\USERNAME\Documents\Rtools)
Please download and install the appropriate version of Rtools before proceeding:
https://cran.rstudio.com/bin/windows/Rtools/
Warning in install.packages :
  package 'htmltab' is not available for this version of R
A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
```

**Expected behavior**
Should be able to install `rtools` using `install.rtools()` completely from within R, using packages that can be found on CRAN.

**Comment by burgerga** [comment]
installr on CRAN is not yet updated to the latest version, use `remotes::install_github("talgalili/installr")` to install the development version which doesn't rely on htmltab anymore

**Comment by dturkenk** [comment]
Thanks. I should have realized to check there first.

**Comment by burgerga** [comment]
Should be on CRAN now
