### ISSUE TITLE
installr should be installable on all platforms

### ISSUE THREAD

**Issue by hadley** [talgalili/installr#164]
It might not do anything, but you should be able to install it — otherwise it's a pain if a mac or linux user wants to contribute to a package that uses installr.

**Comment by talgalili** [comment]
Thanks for the ping Hadley, it's always good to e-see you online.

I agree with your comment (in fact, I've moved to linux and mac and wasn't
able to comfortably update installr in the past couple of years).

I'll take your feedback as signal to fix this - and will get around to it
in the next 3 weeks.
I'll update here once it's done.

Cheers,
T

**Comment by talgalili** [comment]
@hadley  - I've now updated installr so that it should be possible to install it on linux/mac. I'm running more tests and once done, I'll upload installr 0.23.0 to CRAN.

I'd be honored for any PR from you :)

T

**Comment by talgalili** [comment]
installr version 0.23.2 is now on CRAN (and is installable on all platforms :) )

**Comment by talgalili** [comment]
Thanks for the ping. Feel free to suggest a PR with this change :)
