### ISSUE TITLE
Could not find any R installation on your system

### ISSUE THREAD

**Issue by Cs-med** [talgalili/installr#169]
Getting this issue

> R.home()
[1] "/Library/Frameworks/R.framework/Resources"

> updater()
Error in winDialog(type = "ok", message = message_text) : 
  could not find function "winDialog"
In addition: Warning message:
In get.installed.R.folders() :
  Could not find any R installation on your system. (You might have installed your R version on 'c:\R' without sub folders...

**Comment by burgerga** [comment]
Looks like you're using Mac OS, but installr only supports Windows (sorry)
