### ISSUE TITLE
problems updating R on MacOs

### ISSUE THREAD

**Issue by faizt91** [talgalili/installr#170]
I´m trying to update R from the console, but when I run:

 `updater()`

I get this error:

Error in winDialog(type = "ok", message = message_text) : 
  could not find function "winDialog"
In addition: Warning message:
In get.installed.R.folders() :
  Could not find any R installation on your system. (You might have installed your R version on 'c:\R' without sub folders...

**Comment by talgalili** [comment]
installr is not made for Mac, only Windows.
Try the "updateR" package (it's on github)
