### ISSUE TITLE
R patched versions

### ISSUE THREAD

**Issue by tchevri** [talgalili/installr#171]
**Is your feature request related to a problem? Please describe.**
I tried to install the package `XLConnect` and it crashes. The solution stated online is to upgrade `R` to the latest patched version.
However, I can see that:
<html>
<body>
<div class="f4 text-normal" style="box-sizing: border-box; font-size: 16px !important; font-weight: 400; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a title="R/installRtools.R" data-hydro-click="{&quot;event_type&quot;:&quot;search_result.click&quot;,&quot;payload&quot;:{&quot;page_number&quot;:1,&quot;per_page&quot;:10,&quot;query&quot;:&quot;patch&quot;,&quot;result_position&quot;:1,&quot;click_id&quot;:8501831,&quot;result&quot;:{&quot;id&quot;:8501831,&quot;global_relay_id&quot;:&quot;MDEwOlJlcG9zaXRvcnk4NTAxODMx&quot;,&quot;model_name&quot;:&quot;Repository&quot;,&quot;url&quot;:&quot;https://github.com/talgalili/installr/blob/5c68d0e0e4cffd7e6c2ab104963375bf3b59fe12/R/installRtools.R&quot;},&quot;originating_url&quot;:&quot;https://github.com/talgalili/installr/search?q=patch&quot;,&quot;user_id&quot;:27081211}}" data-hydro-click-hmac="55cf8eb5a4e56f5163de2b177b950e7f71fa12881ae0a7aa2f3f11d4cfe61d94" href="https://github.com/talgalili/installr/blob/5c68d0e0e4cffd7e6c2ab104963375bf3b59fe12/R/installRtools.R" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: underline; transition: color 80ms cubic-bezier(0.33, 1, 0.68, 1) 0s, background-color, box-shadow, border-color;">R/installRtools.R</a></div><div class="file-box blob-wrapper my-1" style="box-sizing: border-box; margin-top: 4px !important; margin-bottom: 4px !important; overflow: auto hidden; border: 1px solid var(--color-border-default); border-radius: 6px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

38 | #' @param check_r_update checks if there is an R update available (ignores patch versions),
-- | --

</div>
</body>
</html>

meaning `installr` will ignore patched version when looking for new versions. Is there a reason for this?

**Describe the solution you'd like**
I'd love it if patched version would be entertained as part of the search for updates. At a minimum a parameter override to allow users to opt in for including patched versions in their search for an upgrade to their current `R` insall?

**Describe alternatives you've considered**
the alternative is obvious: a manual install - but defeats the purpose of this awesome package, which i have been using nearly exclusively to maintain my `R` setup for many years - many thanks for that.

**Additional context**
none. just another thank you for putting together this awesome package.

**Comment by burgerga** [comment]
This is in the function that installs Rtools, not R itself. This is because Rtools compatibility (https://cran.r-project.org/bin/windows/Rtools/history.html) changes only with minor versions.
The function `updateR` (https://github.com/talgalili/installr/blob/master/R/updateR.R#L720) will not ignore patch versions

**Comment by talgalili** [comment]
I agree with @burgerga 

Closing.
