### ISSUE TITLE
Could not find any R installation on your system.

### ISSUE THREAD

**Issue by Jiayi-Zheng** [talgalili/installr#186]
Hello, I was using trying to install R4.3 in a newly created conda environment (my base env has R4.1, but a package requires R4.3). 

However, it told me 
```
> updateR()
Error in winDialog(type = "ok", message = message_text) :
  could not find function "winDialog"
In addition: Warning message:
In get.installed.R.folders() :
  Could not find any R installation on your system. (You might have installed your R version on 'c:\R' without sub folders...
> R.version.string
[1] "R version 4.1.0 (2021-05-18)"
> R.home()
[1] "/opt/R/4.1.0/lib/R"
> list.files(R.home())
 [1] "bin"          "COPYING"      "doc"          "etc"          "include"
 [6] "lib"          "library"      "modules"      "share"        "SVN-REVISION"
```

Is there a way I can specify the R installation path so that it knows where to get the R installation...?

Thank you!

**Comment by burgerga** [comment]
If `R.home()` is in `/opt` you're likely on Linux. `installr` is a Windows only package

**Comment by burgerga** [comment]
(ah I see conda, it also doesn't work there. Use conda to update it)
