### ISSUE TITLE
Add the IP2Location.io API

### ISSUE THREAD

**Issue by ip2location-com** [talgalili/installr#189]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Add the IP2Location.io API as an alternative service to the _geo_functions.R_ file.

**Describe alternatives you've considered**
No.

**Additional context**
IP2Location.io API could be a good alternative geolocation provider to provide users with more choices. It provides basic information such as country, region, city, latitude and longitude, ASN and AS, and WHOIS information for a domain.

User can sign up for a free API key, or use the keyless API to get started. There is a limit of 500 free queries per day without an API key. If using an API key with the free plan, users can perform 30,000 queries per month.

For more information, you can check our documentation at https://www.ip2location.io/ip2location-documentation. Hope you can consider adding this API as an option into your project.

**Comment by talgalili** [comment]
Thanks. Do you want to implement it?

**Comment by ip2location-com** [comment]
Hi talgalili,

Is it ok for you to let us make the modification for geo_functions.R file and create the PR for it?

**Comment by talgalili** [comment]
Sure

**Comment by ip2location-com** [comment]
Hi talgalili,

Thanks. We have created the pull request for it.
