### ISSUE TITLE
Not able to download installr

### ISSUE THREAD

**Issue by moneeeeeee** [talgalili/installr#192]
**Describe the bug**
" Warning message:
package ‘installr’ was built under R version 4.4.1 "

**To Reproduce**

Learn how to make a great R reproducible example in the following URL:
https://stackoverflow.com/a/5963610/256662

And please supply us with such information so that we will be able to help you with solving the issue.
I have R version 4.4.0 and want to update it to 4.4.1 instead but am just worried about the already installed packages. I wanted to update it but I keep getting the error when I try to load it after successfully installing.
I use RStudio.

**Expected behavior**
Wanted to update R and move and all packages to not hurt my previous files.

**Comment by talgalili** [comment]
Please paste

sessionInfo()

Notice that installr is only for Windows.

**Comment by burgerga** [comment]
This isn't a problem, it just tells you that the packages you are installing were created with a newer version of R. This also happens without `installr`. If you want the message to go away, update R to 4.4.1
