### ISSUE TITLE
installr error

### ISSUE THREAD

**Issue by aml21** [talgalili/installr#193]
**Describe the bug**
Hi, I am new using RStudio, I tried to update Rstudio with this tutotial: 

https://www.r-statistics.com/2015/06/a-step-by-step-screenshots-tutorial-for-upgrading-r-on-windows/

And RStudio show me the next warning:

> install.packages("instalr")
Installing package into ‘C:/Users/adam2/AppData/Local/R/win-library/4.4’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘instalr’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

**Comment by burgerga** [comment]
You have a typo "instal**l**r"
