### ISSUE TITLE
Request install.awsCLI

### ISSUE THREAD

**Issue by dnlbrky** [talgalili/installr#20]
I would like to create R scripts for other R users that make use of the Amazon Web Services (AWS) Command Line Interface (CLI).  For instance, the script might use the system() function to call the AWS CLI, launch an Elastic MapReduce (EMR) cluster, and crunch some data.

It would be great to have a simple way to make sure the AWS CLI is installed on the local machine.

**Comment by talgalili** [comment]
Hi dnlbrky,
Sorry for responding only now.
Did you end up writing some of the functions you mentioned?

**Comment by dnlbrky** [comment]
Yes, but I'm using them as part of another package I created for internal use.  When I get time I'd like to either post an AWS package on Github/CRAN, or take out the commands that check for and install the CLI and submit them as pull requests to installr.

**Comment by talgalili** [comment]
Either one sounds good - good luck :)
