### ISSUE TITLE
argument name

### ISSUE THREAD

**Issue by BerryBoessenkool** [talgalili/installr#23]
download_RStudio_CRAN_data has the argument 'massage' - that should be message, I think.

And Hadley recommends using message instead of cat, so people can catch messages if they do not want to see them. Maybe, if you have spare time sometime in the future (like 2050 or so;-)), you can replace that...

**Comment by talgalili** [comment]
You're welcome to change it in the code, send a pull request, and I'll do it :)

**Comment by BerryBoessenkool** [comment]
that was easy - just made my first pull request (Yeah, I know, way overdue).
I hope I did everything correctly.

Berry

Date: Wed, 4 Feb 2015 07:42:41 -0800

**Comment by talgalili** [comment]
Good job :+1:
