### ISSUE TITLE
files ‘bin/R.exe’, ‘bin/Rscript.exe’ have the wrong MD5 checksums

### ISSUE THREAD

**Issue by jimhulsebus** [talgalili/installr#30]
Loading required package: tools
files ‘bin/R.exe’, ‘bin/Rscript.exe’ have the wrong MD5 checksums

**Comment by talgalili** [comment]
Thanks.
You upgraded from which to which R version?

**Comment by jimhulsebus** [comment]
3.1.3 .  Failed twice with same message from RStudio, so I tried from R. R
3.2.0 installed ok, but packages didn't get transferrred and updated.

**Comment by talgalili** [comment]
o.k.
What do you get when typing:

```r
 R.home()
```
?

**Comment by VMJim** [comment]
First of all, thanks for filling the void of user-unfriendly R updating.

I had the exact same issue while upgrading from 3.1.2 to 3.2.0.

My `R.home()` is 
"C:/PROGRA~1/R/R-32~1.0"

**Comment by talgalili** [comment]
Thanks VMSim,
I know the package doesn't always work from RStudio (and I'm not sure it is trivial/crucial to fix). But I would be happy to know what happened with the packages. Do you have a log of the massages you got in the console you could send?

**Comment by VMJim** [comment]
I'm glad you asked about the packages, because they were not copied/installed in the new library directory: I had to copy/paste them by hand. This failed at first because apparently there are two (!?) library paths, i.e. `.libPaths()` returns: 
"C:/Users/Jim/Documents/R/win-library/3.2" "C:/Program Files/R/R-3.2.0/library"

As for the installation logs.. I did not save them and have no clue how to retrieve them now.

-- Jim

**Comment by jimhulsebus** [comment]
You have 2 Jims here so may be a bit confusing. After installing and
uninstalling 3.2, I gave up for a couple of days and went back to 3.1.3.
Today, I installed 3.2.0 again using R rather than RStudio. The install
when fine and looks like about 50 of 350 packages were transferred an
updated. I can work from there. Thanks for the help.

**Comment by vardakism** [comment]
Hi all, 
I got the same error : ‘bin/Rscript.exe’ have the wrong MD5 checksums. I am running in win 7 and I have updated the version 3.1.3 to 3.2.0 from R (not Rstudio). Before that it was always working..

**Comment by datasci-nmd5** [comment]
Same error here today trying to upgrade from 3.1.2 to 3.2.0 using R (not RStudio) on Windows 8.

R.home() returns: "C:/PROGRA~1/R/R-32~1.0"

Error Message: 
files ‘bin/R.exe’, ‘bin/Rscript.exe’ have the wrong MD5 checksums
No packages to copy.  Goodbye :) 

Data Provided when using bug.report(package = 'installr'):
Package: installr
 Version: 0.15.3
 Maintainer: Tal Galili <tal.galili@gmail.com>
 Built: R 3.2.0; ; 2015-05-07 22:43:26 UTC; windows

R Version:
 platform = x86_64-w64-mingw32
 arch = x86_64
 os = mingw32
 system = x86_64, mingw32
 status = 
 major = 3
 minor = 1.2
 year = 2014
 month = 10
 day = 31
 svn rev = 66913
 language = R
 version.string = R version 3.1.2 (2014-10-31)
 nickname = Pumpkin Helmet

Windows 8 x64 (build 9200)

Locale:
 LC_COLLATE=English_United States.1252;LC_CTYPE=English_United States.1252;LC_MONETARY=English_United States.1252;LC_NUMERIC=C;LC_TIME=English_United States.1252

Search Path:
 .GlobalEnv, package:tools, package:installr, package:plyr, package:data.table, package:stats, package:graphics,
 package:grDevices, package:utils, package:datasets, package:methods, Autoloads, package:base

**Comment by talgalili** [comment]
Hello everyone, sorry for taking so long to respond.

I believe I "fixed" this issue with the recent installr, you can get it from github using:

if (!require('devtools')) install.packages('devtools'); # make sure you have Rtools installed first! if not, then run:
#install.packages('installr')
#install.Rtools()
devtools::install_github('talgalili/installr')

**The good news: I believe all of you got a working version of R.**

datasci-nmd5 - I suspect that what you got was a "warning" not an "error" (if it was an error, it wouldn't be able to get the next message regarding the copying of packages).

This warning message means that you installed R, and that a check that was done found that some files may have not been installed correctly. 
I reported this on the R-devel mailing list, but I suspect that **there is no issue** with your R installation, and that this is a **false alarm**.

With regards,
Tal
