### ISSUE TITLE
I am not sure if this is an issue with updater

### ISSUE THREAD

**Issue by mwahab1** [talgalili/installr#31]
I had R 3.1.2 and started the update using http://www.r-statistics.com/2013/03/updating-r-from-r-on-windows-using-the-installr-package/ 

as guidance.

It indicated 3.2 was available and I selected yes to be upgraded.
It said checksums didn't match...but proceeded to install.
Asked me if I wanted to update packages. I selected yes...but it came back and  said no packages to be moved(even though I thought I had said yes). Then it stalled for a while.....and when it finally started a new R3.2 session...the list of packages was missing most of packages that I had installed.

Instead of uninstalling etc...I thought I would be clever and rerun (and select a different folder for installation). It reinstalled...but then produced the following:

===============

Running the installer now...

Installation status:  TRUE . Removing the file:
 C:\Users\w\AppData\Local\Temp\RtmpCeivwP/R-3.2.0-win.exe 
 (In the future, you may keep the file by setting keep_install_file=TRUE) 
Loading required package: tools
files ‘bin/R.exe’, ‘bin/Rscript.exe’ have the wrong MD5 checksums

We can not seem to find the location if the new R you have installed.
The rest of the updating process is aborted, please take care to copy
your packages to the new R installation.

==============================
Am a newbie to R ...will probably be finding out how to move packages :-)

**Comment by mwahab1** [comment]
R version 3.1.2 (2014-10-31) -- "Pumpkin Helmet"
Copyright (C) 2014 The R Foundation for Statistical Computing
Platform: i386-w64-mingw32/i386 (32-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> bug.report(package = 'installr') 
Package: installr
 Version: 0.15.3
 Maintainer: Tal Galili <tal.galili@gmail.com>
 Built: R 3.2.0; ; 2015-05-12 22:37:16 UTC; windows

R Version:
 platform = i386-w64-mingw32
 arch = i386
 os = mingw32
 system = i386, mingw32
 status = 
 major = 3
 minor = 1.2
 year = 2014
 month = 10
 day = 31
 svn rev = 66913
 language = R
 version.string = R version 3.1.2 (2014-10-31)
 nickname = Pumpkin Helmet

Windows 7 x64 (build 7601) Service Pack 1

Locale:
 LC_COLLATE=English_United States.1252;LC_CTYPE=English_United States.1252;LC_MONETARY=English_United States.1252;LC_NUMERIC=C;LC_TIME=English_United States.1252

Search Path:
 .GlobalEnv, package:stats, package:graphics, package:grDevices,
 package:utils, package:datasets, package:methods, Autoloads,
 package:base


This package has a bug submission web page, which we will now attempt
to open.  The information above may be useful in your report. If the web
page doesn't work, you should send email to the maintainer,
Tal Galili <tal.galili@gmail.com>.
>

**Comment by talgalili** [comment]
This is resolved in installr 0.16.0
