### ISSUE TITLE
checksum

### ISSUE THREAD

**Issue by PedroM1** [talgalili/installr#32]
After installing from R command line this message appears: "  There was some problem with installing R.  Some files are not what they should be (e.g: check MD5 sums did not pass all the tests). "

System: Windows

*** Full dump:

> install.R()
trying URL 'http://cran.rstudio.com/bin/windows/base/R-3.2.0-win.exe'
Content type 'application/x-msdos-program' length 64980781 bytes (62.0 MB)
opened URL
downloaded 62.0 MB

The file was downloaded succesfully into:
 C:\Users\e337652\AppData\Local\Temp\Rtmpo5XY8m/R-3.2.0-win.exe 

Running the installer now...

Installation status:  TRUE . Removing the file:
 C:\Users\e337652\AppData\Local\Temp\Rtmpo5XY8m/R-3.2.0-win.exe 
 (In the future, you may keep the file by setting keep_install_file=TRUE) 
files ‘bin/R.exe’, ‘bin/Rscript.exe’ have the wrong MD5 checksums
[1] TRUE
Warning message:
In install.R() :
  There was some problem with installing R.  Some files are not what they should be (e.g: check MD5 sums did not pass all the tests). 
  You can try installing R again (either manually or through install.R()), 
  and if the problem persists you can file a bug report by running:  bug.report(package = 'installr')

**Comment by talgalili** [comment]
Thanks for the report, this was already fixed in the recent installr version, after issue #30 was reported.

I'll try to get the latest installr to go on CRAN so others won't suffer from it as much.

Thanks,
Tal
