### ISSUE TITLE
Ubuntu installr not available for 3.1.2?

### ISSUE THREAD

**Issue by evohnave** [talgalili/installr#33]
Running RStudio 0.99.446 and R 3.1.2 on Ubuntu 15.04.  Keep getting error message that installr not available for R version 3.1.2 after install.packages("installr")  Other packages install OK... Issue?

**Comment by talgalili** [comment]
installr is intended for Windows, not OSX or Ubuntu (sadly). But it should be able to install itself. Could you paste the exact error you got?

**Comment by evohnave** [comment]
Tal,

I feared this might be the explanation... I really enjoy installr on my
Windows machines.

I am at work and my Ubuntu laptop is at home.  I'll send you the exact
error tonight.

Cheers,

Eric

**Comment by talgalili** [comment]
Since I don't use linux (sadly for me), I never wrapped the updating process for ubuntu.
However, if you know the script you run, and can run it from R using: ?system then it could (in the future) be incorporated into installr (but no one has ever made the effort).  I am open for patches to have installr help other OSs as well.

**Comment by evohnave** [comment]
I look into it... I'm glad to help and offer suggestions.

I'm new to linux/Ubuntu but need it for a class and had an old laptop that
I wasn't using because Windows 7 ran really slow on it.  Ubuntu runs much
faster, so you may consider it if you have an old box that you just can't
throw away...

Cheers,

Eric

**Comment by AnjaEggert** [comment]
I also just wanted to install the installr package on linux (R 3.1.2). I want to support the initiative to make it applicable on linux. We use R on a linux serve at the institute and want to keep several R versions in parallel, i.e. we would like to move the library from an older R version to the most recent one. I thought that installr is just the right library.  Cheers, Anja

**Comment by talgalili** [comment]
Sorry @AnjaEggert  - installr is currently only available for Windows users.
If you figure out an easy way to do what you want from R - I am open for code commits to the package.

Best,
Tal

**Comment by evohnave** [comment]
I wasn't able to make a script, but here's the way to do it:

Note: there may be a typo in here... I can't remember if I had one or not
or if I went back into my post to correct it, and if there is it is
probably in the deb line.  The links help.

Of course you could just google stackoverflow upgrade r ubuntu... (or go
here
<http://stackoverflow.com/questions/10476713/how-to-upgrade-r-in-ubuntu>)

First, make sure your sources.list has an appropriate deb line.

Open up your sources list:
sudo gedit /etc/apt/sources.list

Add (or check) that the following is in the list:
deb https://{your mirror site}/bin/linux/ubuntu vivid/

Use whatever site you want for {your mirror site} from the CRAN List Of
Mirrors <https://cran.r-project.org/mirrors.html>.

Since I'm using Ubuntu 15.04 "Vivid Vervet" I use ubuntu vivid in the link
above.  If you're using a different version you'll change that portion of
the URL accordingly.

Next fetch the secure APT key with
gpg --keyserver keyserver.ubuntu.com --recv-key E084DAB9

Feed this key to apt-key with
gpg -a --export E084DAB9 | sudo apt-key add -

Now update your sources and upgrade your installation with
sudo apt-get update && sudo apt-get upgrade
