### ISSUE TITLE
I can't install Rtools

### ISSUE THREAD

**Issue by Tixierae** [talgalili/installr#36]
When I run the command `install.Rtools()` I get `No need to install Rtools - You've got the relevant version of Rtools installed`, however `library(Rtools)` returns `Error in library(Rtools) : there is no package called ‘Rtools’`. If I do `install.packages("Rtools")`, I get the following warning: `Warning in install.packages : package ‘Rtools’ is not available (for R version 3.2.1)`... I should add that I downloaded Rtools from this [page](http://cran.r-project.org/bin/windows/Rtools/) and installed it.

**Comment by talgalili** [comment]
Hi @Tixierae ,
Rtools is not an R package, it is an "external" software package that is designed to allow you to compile things which are related to R. Hence, the errors you get make sense, and are not a BUG.

Tal.

**Comment by Tixierae** [comment]
thanks for the quick reply
