### ISSUE TITLE
Typo in dialogue window

### ISSUE THREAD

**Issue by jaminday** [talgalili/installr#38]
Very minor issue. When updating R environment using `updateR()`, there's a typo in the dialogue window "Would you like to update your **newely** installed packages" (should be *newly*).

![screenclip](https://cloud.githubusercontent.com/assets/1966387/9322660/e7f2a436-45b9-11e5-9dcf-43dd65576250.png)

**Comment by talgalili** [comment]
Thanks Jasmin, I've now fixed it for the next release.

Best,
Tal

**Comment by jaminday** [comment]
No problem.
