### ISSUE TITLE
installr "can not seem to find the location if the new R you have installed"

### ISSUE THREAD

**Issue by bharris-fs** [talgalili/installr#39]
When upgrading on W7 from R 3.2.1 to 3.2.2, installr seems to get lost after installing base R and before moving over the library.  3.2.1 seemed to be working prior to this upgrade, and I tried the upgrade twice, once from the Rgui console and once from the menu pick.

Incidentally, I never saw the pop-up mentioned in step 9 of http://www.r-statistics.com/2015/06/a-step-by-step-screenshots-tutorial-for-upgrading-r-on-windows/, but installr seems to have progressed almost to step 11 (I never saw the "I am now copying" message).  When I upgraded to 3.2.1, it also never showed that pop-up; it just ran silently for a long time (apparently copying packages) and then completed.

Trivially, there seems to be a typo in a message from installr (see below): "We can not seem to find the location if the new R you have installed."  (should be "of")

From the console in RGui:

> library(installr)

Welcome to installr version 0.16.0

More information is available on the installr project website:
https://github.com/talgalili/installr/

Contact: <tal.galili@gmail.com>
Suggestions and bug-reports can be submitted at: https://github.com/talgalili/installr/issues

                        To suppress this message use:
                        suppressPackageStartupMessages(library(installr))

Warning message:
package ‘installr’ was built under R version 3.2.2 
> updateR()
Installing the newest version of R,
 please wait for the installer file to be download and executed.
 Be sure to click 'next' as needed...
trying URL 'http://cran.rstudio.com/bin/windows/base/R-3.2.2-win.exe'
Content type 'application/x-msdos-program' length 65288451 bytes (62.3 MB)
downloaded 62.3 MB

The file was downloaded succesfully into:
 C:\Users\measadmin\AppData\Local\Temp\RtmpYz1Ixg/R-3.2.2-win.exe 

Running the installer now...

Installation status:  TRUE . Removing the file:
 C:\Users\measadmin\AppData\Local\Temp\RtmpYz1Ixg/R-3.2.2-win.exe 
 (In the future, you may keep the file by setting keep_install_file=TRUE) 
Warning: files ‘library/KernSmooth/tests/bkfe.R’, ‘library/MASS/tests/BankWages.rda’, ‘library/MASS/tests/Examples/MASS-Ex.Rout.save’, ‘library/MASS/tests/confint.R’, ‘library/MASS/tests/fitdistr.R’, ‘library/MASS/tests/fitdistr.Rout.save’, ‘library/MASS/tests/glm.nb.R’, ‘library/MASS/tests/hubers.R’, ‘library/MASS/tests/lme.R’, ‘library/MASS/tests/polr.R’, ‘library/MASS/tests/profile.R’, ‘library/MASS/tests/regression.R’, ‘library/MASS/tests/regression.Rout.save’, ‘library/MASS/tests/rlm.R’, ‘library/MASS/tests/scripts.R’, ‘library/Matrix/tests/Class+Meth.R’, ‘library/Matrix/tests/Simple.R’, ‘library/Matrix/tests/abIndex-tsts.R’, ‘library/Matrix/tests/base-matrix-fun.R’, ‘library/Matrix/tests/bind.R’, ‘library/Matrix/tests/bind.Rout.save’, ‘library/Matrix/tests/dg_Matrix.R’, ‘library/Matrix/tests/dpo-test.R’, ‘library/Matrix/tests/dtpMatrix.R’, ‘library/Matrix/tests/factorizing.R’, ‘library/Matrix/tests/group-methods.R’, ‘library/Matrix/tests/indexing.R’, ‘library/Matrix/tests/indexing.Rout.save’, ‘library/Matrix/tests/matprod.R’, ‘library/Matrix/tests/matr-exp.R’, ‘library/Matrix/tests/other-pkgs.R’, ‘library/Matrix/tests/spModel.matrix.R’, ‘library/Matrix/tests/validObj.R’, ‘library/Matrix/tests/write-read.R’, ‘library/boot/tests/Examples/boot-Ex.Rout.save’, ‘library/cluster/tests/agnes-ex.R’, ‘library/cluster/tests/agnes-ex.Rout.save’, ‘library/cluster/tests/clara-NAs.R’, ‘library/cluster/tests/clara-NAs.Rout.save’, ‘library/cluster/tests/clara-ex.R’, ‘library/cluster/tests/clara.R’, ‘library/cluster/tests/clara.Rout.save’, ‘library/cluster/tests/clusplot-out.R’, ‘library/cluster/tests/clusplot-out.Rout.save’, ‘library/cluster/tests/daisy-ex.R’, ‘library/cluster/tests/daisy-ex.Rout.save’, ‘library/cluster/tests/diana-boots.R’, ‘library/cluster/tests/diana-ex.R’, ‘library/cluster/tests/diana-ex.Rout.save’, ‘library/cluster/tests/ellipsoid-ex.R’, ‘library/cluster/tests/ellipsoid-ex.Rout.save’, ‘library/cluster/tests/fanny-ex.R’, ‘library/cluster/tests/mona.R’, ‘library/cluster/tests/mona.Rout.save’, ‘library/cluster/tests/pam.R’, ‘library/cluster/tests/pam.Rout.save’, ‘library/cluster/tests/silhouette-default.R’, ‘library/cluster/tests/silhouette-default.Rout.save’, ‘library/cluster/tests/sweep-ex.R’, ‘library/codetools/tests/tests.R’, ‘library/foreign/tests/Alfalfa.xpt’, ‘library/foreign/tests/MLLabelsWithNotesChar.dta’, ‘library/foreign/tests/OneVarTwoValLabels.dta’, ‘library/foreign/tests/S3.R’, ‘library/foreign/tests/S3.Rout.save’, ‘library/foreign/tests/arff.R’, ‘library/foreign/tests/arff.Rout.save’, ‘library/foreign/tests/auto8.dta’, ‘library/foreign/tests/compressed.dta’, ‘library/foreign/tests/contact-lenses.arff’, ‘library/foreign/tests/create-dumpdata.S’, ‘library/foreign/tests/datefactor.dta’, ‘library/foreign/tests/download.R’, ‘library/foreign/tests/dumpdata’, ‘library/foreign/tests/electric.por’, ‘library/foreign/tests/electric.sav’, ‘library/foreign/tests/ex1-51.mtp’, ‘library/foreign/tests/keep/codefile.sps’, ‘library/foreign/tests/keep/datafile.dat’, ‘library/foreign/tests/minitab.R’, ‘library/foreign/tests/minitab.Rout.save’, ‘library/foreign/tests/mval_bug.R’, ‘library/foreign/tests/mval_bug.Rout.save’, ‘library/foreign/tests/mval_bug.sav’, ‘library/foreign/tests/mySobj’, ‘library/foreign/tests/octave.R’, ‘library/foreign/tests/octave.Rout.save’, ‘library/foreign/tests/octave.dat’, ‘library/foreign/tests/octave.m’, ‘library/foreign/tests/pbc.por’, ‘library/foreign/tests/pbc.sav’, ‘library/foreign/tests/pbc.sys’, ‘library/foreign/tests/pbcold.sav’, ‘library/foreign/tests/pc5.dta’, ‘library/foreign/tests/sample100.por’, ‘library/foreign/tests/sample100.sav’, ‘library/foreign/tests/sas.R’, ‘library/foreign/tests/spss.R’, ‘library/foreign/tests/spss.Rout.save’, ‘library/foreign/tests/spss_long.sav’, ‘library/foreign/tests/stata.R’, ‘library/foreign/tests/stata.Rout.save’, ‘library/foreign/tests/stata7se.dta’, ‘library/foreign/tests/stata8mac.dta’, ‘library/foreign/tests/sun6.dta’, ‘library/foreign/tests/test.xpt’, ‘library/foreign/tests/testEmpty.R’, ‘library/foreign/tests/testEmpty.Rout.save’, ‘library/foreign/tests/testEmpty.xpt’, ‘library/foreign/tests/tsdumpdata’, ‘library/foreign/tests/writeForeignSPSS.R’, ‘library/foreign/tests/writeForeignSPSS.Rout.save’, ‘library/foreign/tests/xport.R’, ‘library/foreign/tests/xport.Rout.save’, ‘library/foreign/tests/xxx12.dta’, ‘library/lattice/tests/MASSch04.R’, ‘library/lattice/tests/dates.R’, ‘library/lattice/tests/dotplotscoping.R’, ‘library/lattice/tests/fontsize.R’, ‘library/lattice/tests/levelplot.R’, ‘library/lattice/tests/scales.R’, ‘library/lattice/tests/temp.R’, ‘library/lattice/tests/test.R’, ‘library/lattice/tests/wireframe.R’, ‘library/mgcv/po/po/LC_MESSAGES/R-mgcv.mo’, ‘library/mgcv/po/po/LC_MESSAGES/mgcv.mo’, ‘library/nlme/tests/anova.gls.R’, ‘library/nlme/tests/augPred_lab.R’, ‘library/nlme/tests/augPredmissing.R’, ‘library/nlme/tests/coef.R’, ‘library/nlme/tests/contrMat.R’, ‘library/nlme/tests/data.frame.R’, ‘library/nlme/tests/deparse.R’, ‘library/nlme/tests/fitted.R’, ‘library/nlme/tests/getData.R’, ‘library/nlme/tests/gls.R’, ‘library/nlme/tests/lmList.R’, ‘library/nlme/tests/lme.R’, ‘library/nlme/tests/lme.Rout.save’, ‘library/nlme/tests/missing.R’, ‘library/nlme/tests/missing.Rout.save’, ‘library/nlme/tests/nlme.R’, ‘library/nlme/tests/nlme.Rout.save’, ‘library/nlme/tests/nlme2.R’, ‘library/nlme/tests/predict.lme.R’, ‘library/nlme/tests/ss2.rda’, ‘library/nlme/tests/update.R’, ‘library/nlme/tests/updateLme.R’, ‘library/nlme/tests/varIdent.R’, ‘library/rpart/tests/Examples/rpart-Ex.Rout.save’, ‘library/rpart/tests/backticks.R’, ‘library/rpart/tests/backticks.Rout.save’, ‘library/rpart/tests/cost.R’, ‘library/rpart/tests/cost.Rout.save’, ‘library/rpart/tests/cptest.R’, ‘library/rpart/tests/cptest.Rout.save’, ‘library/rpart/tests/data.stagec’, ‘library/rpart/tests/priors.R’, ‘library/rpart/tests/priors.Rout.save’, ‘library/rpart/tests/rescale.R’, ‘library/rpart/tests/rescale.Rout.save’, ‘library/rpart/tests/testall.R’, ‘library/rpart/tests/testall.Rout.save’, ‘library/rpart/tests/treble.R’, ‘library/rpart/tests/treble.Rout.save’, ‘library/rpart/tests/treble2.R’, ‘library/rpart/tests/treble2.Rout.save’, ‘library/rpart/tests/treble3.R’, ‘library/rpart/tests/treble3.Rout.save’, ‘library/rpart/tests/treble4.R’, ‘library/rpart/tests/treble4.Rout.save’, ‘library/rpart/tests/usersplits.R’, ‘library/rpart/tests/usersplits.Rout.save’, ‘library/rpart/tests/xpred1.R’, ‘library/rpart/tests/xpred1.Rout.save’, ‘library/rpart/tests/xpred2.R’, ‘library/rpart/tests/xpred2.Rout.save’, ‘library/spatial/tests/Examples/spatial-Ex.Rout.save’, ‘library/survival/tests/aareg.R’, ‘library/survival/tests/aareg.Rout.save’, ‘library/survival/tests/anova.R’, ‘library/survival/tests/anova.Rout.save’, ‘library/survival/tests/bladder.R’, ‘library/survival/tests/bladder.Rout.save’, ‘library/survival/tests/book1.R’, ‘library/survival/tests/book1.Rout.save’, ‘library/survival/tests/book2.R’, ‘library/survival/tests/book2.Rout.save’, ‘library/survival/tests/book3.R’, ‘library/survival/tests/book3.Rout.save’, ‘library/survival/tests/book4.R’, ‘library/survival/tests/book4.Rout.save’, ‘library/survival/tests/book5.R’, ‘library/survival/tests/book5.Rout.save’, ‘library/survival/tests/book6.R’, ‘library/survival/tests/book6.Rout.save’, ‘library/survival/tests/book7.R’, ‘library/survival/tests/book7.Rout.save’, ‘library/survival/tests/cancer.R’, ‘library/survival/tests/cancer.Rout.save’, ‘library/survival/tests/clogit.R’, ‘library/survival/tests/clogit.Rout.save’, ‘library/survival/tests/concordance.R’, ‘library/survival/tests/concordance.Rout.save’, ‘library/survival/tests/counting.R’, ‘library/survival/tests/counting.Rout.save’, ‘library/survival/tests/coxsurv.R’, ‘library/survival/tests/coxsurv.Rout.save’, ‘library/survival/tests/coxsurv2.R’, ‘library/survival/tests/coxsurv2.Rout.save’, ‘library/survival/tests/coxsurv3.R’, ‘library/survival/tests/coxsurv3.Rout.save’, ‘library/survival/tests/coxsurv4.R’, ‘library/survival/tests/coxsurv4.Rout.save’, ‘library/survival/tests/data.capacitor’, ‘library/survival/tests/data.cracks’, ‘library/survival/tests/data.donnell’, ‘library/survival/tests/data.fluid’, ‘library/survival/tests/data.interval’, ‘library/survival/tests/data.motor’, ‘library/survival/tests/data.peterson’, ‘library/survival/tests/data.rat2’, ‘library/survival/tests/data.smoke’, ‘library/survival/tests/data.turbine’, ‘library/survival/tests/data.valve’, ‘library/survival/tests/detail.R’, ‘library/survival/tests/detail.Rout.save’, ‘library/survival/tests/difftest.R’, ‘library/survival/tests/difftest.Rout.save’, ‘library/survival/tests/doaml.R’, ‘library/survival/tests/doaml.Rout.save’, ‘library/survival/tests/doweight.R’, ‘library/survival/tests/doweight.Rout.save’, ‘library/survival/tests/expected.R’, ‘library/survival/tests/expected.Rout.save’, ‘library/survival/tests/expected2.R’, ‘library/survival/tests/expected2.Rout.save’, ‘library/survival/tests/factor.R’, ‘library/survival/tests/factor.Rout.save’, ‘library/survival/tests/factor2.R’, ‘library/survival/tests/factor2.Rout.save’, ‘library/survival/tests/fr_cancer.R’, ‘library/survival/tests/fr_cancer.Rout.save’, ‘library/survival/tests/fr_kidney.R’, ‘library/survival/tests/fr_kidney.Rout.save’, ‘library/survival/tests/fr_lung.R’, ‘library/survival/tests/fr_lung.Rout.save’, ‘library/survival/tests/fr_ovarian.R’, ‘library/survival/tests/fr_ovarian.Rout.save’, ‘library/survival/tests/fr_rat1.R’, ‘library/survival/tests/fr_rat1.Rout.save’, ‘library/survival/tests/fr_rat2.R’, ‘library/survival/tests/fr_rat2.Rout.save’, ‘library/survival/tests/fr_resid.R’, ‘library/survival/tests/fr_resid.Rout.save’, ‘library/survival/tests/fr_simple.R’, ‘library/survival/tests/fr_simple.Rout.save’, ‘library/survival/tests/frailty.R’, ‘library/survival/tests/frailty.Rout.save’, ‘library/survival/tests/frank.R’, ‘library/survival/tests/frank.Rout.save’, ‘library/survival/tests/gray1.rda’, ‘library/survival/tests/infcox.R’, ‘library/survival/tests/infcox.Rout.save’, ‘library/survival/tests/jasa.R’, ‘library/survival/tests/jasa.Rout.save’, ‘library/survival/tests/model.matrix.R’, ‘library/survival/tests/model.matrix.Rout.save’, ‘library/survival/tests/mrtest.R’, ‘library/survival/tests/mrtest.Rout.save’, ‘library/survival/tests/nested.R’, ‘library/survival/tests/nested.Rout.save’, ‘library/survival/tests/ovarian.R’, ‘library/survival/tests/ovarian.Rout.save’, ‘library/survival/tests/plot.R’, ‘library/survival/tests/plot1.pdf.save’, ‘library/survival/tests/prednew.R’, ‘library/survival/tests/prednew.Rout.save’, ‘library/survival/tests/pspline.R’, ‘library/survival/tests/pspline.Rout.save’, ‘library/survival/tests/pyear.R’, ‘library/survival/tests/pyear.Rout.save’, ‘library/survival/tests/quantile.R’, ‘library/survival/tests/quantile.Rout.save’, ‘library/survival/tests/r_capacitor.R’, ‘library/survival/tests/r_capacitor.Rout.save’, ‘library/survival/tests/r_donnell.R’, ‘library/survival/tests/r_donnell.Rout.save’, ‘library/survival/tests/r_lung.R’, ‘library/survival/tests/r_lung.Rout.save’, ‘library/survival/tests/r_peterson.R’, ‘library/survival/tests/r_peterson.Rout.save’, ‘library/survival/tests/r_resid.R’, ‘library/survival/tests/r_resid.Rout.save’, ‘library/survival/tests/r_sas.R’, ‘library/survival/tests/r_sas.R.orig’, ‘library/survival/tests/r_sas.Rout.save’, ‘library/survival/tests/r_scale.R’, ‘library/survival/tests/r_scale.Rout.save’, ‘library/survival/tests/r_stanford.R’, ‘library/survival/tests/r_stanford.Rout.save’, ‘library/survival/tests/r_strata.R’, ‘library/survival/tests/r_strata.Rout.save’, ‘library/survival/tests/r_tdist.R’, ‘library/survival/tests/r_tdist.Rout.save’, ‘library/survival/tests/r_user.R’, ‘library/survival/tests/r_user.Rout.save’, ‘library/survival/tests/ratetable.R’, ‘library/survival/tests/ratetable.Rout.save’, ‘library/survival/tests/rounding.R’, ‘library/survival/tests/rounding.Rout.save’, ‘library/survival/tests/singtest.R’, ‘library/survival/tests/singtest.Rout.save’, ‘library/survival/tests/strata2.R’, ‘library/survival/tests/strata2.Rout.save’, ‘library/survival/tests/stratatest.R’, ‘library/survival/tests/stratatest.Rout.save’, ‘library/survival/tests/summary_survfit.R’, ‘library/survival/tests/summary_survfit.Rout.save’, ‘library/survival/tests/surv.R’, ‘library/survival/tests/surv.Rout.save’, ‘library/survival/tests/survfit2.R’, ‘library/survival/tests/survfit2.Rout.save’, ‘library/survival/tests/survreg2.R’, ‘library/survival/tests/survreg2.Rout.save’, ‘library/survival/tests/survtest.R’, ‘library/survival/tests/survtest.Rout.save’, ‘library/survival/tests/testci.R’, ‘library/survival/tests/testci.Rout.save’, ‘library/survival/tests/testci2.R’, ‘library/survival/tests/testci2.Rout.save’, ‘library/survival/tests/testnull.R’, ‘library/survival/tests/testnull.Rout.save’, ‘library/survival/tests/testreg.R’, ‘library/survival/tests/testreg.Rout.save’, ‘library/survival/tests/tiedtime.R’, ‘library/survival/tests/tiedtime.Rout.save’, ‘library/survival/tests/ties.rda’, ‘library/survival/tests/tt.R’, ‘library/survival/tests/tt.Rout.save’, ‘library/survival/tests/turnbull.R’, ‘library/survival/tests/turnbull.Rout.save’ are missing

We can not seem to find the location if the new R you have installed.
The rest of the updating process is aborted, please take care to copy
your packages to the new R installation.
[1] TRUE
Warning messages:
1: In checkMD5sums2(dir = new_R_path, omit_files = files_to_omit_from_MD5) :
  files ‘library/KernSmooth/DESCRIPTION’, ‘library/KernSmooth/Meta/nsInfo.rds’, ‘library/KernSmooth/Meta/package.rds’, ‘library/KernSmooth/NAMESPACE’, ‘library/KernSmooth/R/KernSmooth.rdb’, ‘library/KernSmooth/R/KernSmooth.rdx’, ‘library/KernSmooth/help/KernSmooth.rdb’, ‘library/KernSmooth/help/KernSmooth.rdx’, ‘library/KernSmooth/help/paths.rds’, ‘library/KernSmooth/html/00Index.html’, ‘library/KernSmooth/libs/i386/KernSmooth.dll’, ‘library/KernSmooth/libs/x64/KernSmooth.dll’, ‘library/MASS/DESCRIPTION’, ‘library/MASS/Meta/nsInfo.rds’, ‘library/MASS/Meta/package.rds’, ‘library/MASS/NAMESPACE’, ‘library/MASS/R/MASS.rdb’, ‘library/MASS/R/MASS.rdx’, ‘library/MASS/data/Rdata.rdb’, ‘library/MASS/data/Rdata.rdx’, ‘library/MASS/help/MASS.rdb’, ‘library/MASS/help/MASS.rdx’, ‘library/MASS/help/paths.rds’, ‘library/MASS/html/00Index.html’, ‘library/MASS/libs/i386/MASS.dll’, ‘library/MASS/libs/x64/MASS.dll’, ‘library/Matrix/DESCRIPTION’, ‘library/Matrix/Meta/nsInfo.rds’, ‘library/Matrix/Meta/packa [... truncated]
2: In install.R(to_checkMD5sums = to_checkMD5sums, keep_install_file = keep_install_file,  :
  There was some problem with installing R.  Some files are not what they should be (e.g: check MD5 sums did not pass all the tests). 
  You can try installing R again (either manually or through install.R()), 
  and if the problem persists you can file a bug report by running:  bug.report(package = 'installr') 
> bug.report(package='installr')
Package: installr
 Version: 0.16.0
 Maintainer: Tal Galili <tal.galili@gmail.com>
 Built: R 3.2.2; ; 2015-08-24 02:36:17 UTC; windows

R Version:
 platform = x86_64-w64-mingw32
 arch = x86_64
 os = mingw32
 system = x86_64, mingw32
 status = 
 major = 3
 minor = 2.1
 year = 2015
 month = 06
 day = 18
 svn rev = 68531
 language = R
 version.string = R version 3.2.1 (2015-06-18)
 nickname = World-Famous Astronaut

Windows 7 x64 (build 7601) Service Pack 1

Locale:
 LC_COLLATE=English_United States.1252;LC_CTYPE=English_United States.1252;LC_MONETARY=English_United States.1252;LC_NUMERIC=C;LC_TIME=English_United States.1252

Search Path:
 .GlobalEnv, package:installr, package:stats, package:graphics, package:grDevices, package:utils, package:datasets, package:methods,
 Autoloads, package:base

This package has a bug submission web page, which we will now attempt
to open.  The information above may be useful in your report. If the web
page doesn't work, you should send email to the maintainer,
Tal Galili <tal.galili@gmail.com>.
>

**Comment by bharris-fs** [comment]
With a bit more looking, I discovered that installr seemed to be installing R 3.2.2 in c:/Program Files/R/R-3.2.2 by default.  I manually selected c:/R/R-3.2.2, and it seems to work.  I don't know if that's a bug (wrong default) or an error on my part.  Incidentally, this time it did ask me if I wanted to upgrade packages, etc.

**Comment by talgalili** [comment]
Hi @bharris-fs , this is the default of the R installer (unrelated to the installr package).
It sounds like your issue was just related to the location of your new vs old R folders...
