### ISSUE TITLE
Issue in updating to latest version of R 3.2.2 in windows (64 bit/32 bit)

### ISSUE THREAD

**Issue by aruneral01** [talgalili/installr#41]
Type 'q()' to quit R.

[Previously saved workspace restored]

When looking to install the installr package from the R GUI, I am getting the below warning message"package ‘installr’ is not available (for R version 3.2.1) ". After this warning it quits and doesn't do the update. Does anyone else had this issue?

> install.packages("installr"); library(installr) 
--- Please select a CRAN mirror for use in this session ---
Warning: unable to access index for repository https://cran.cnr.Berkeley.edu/src/contrib
Warning: unable to access index for repository https://cran.cnr.Berkeley.edu/bin/windows/contrib/3.2
Warning message:
package ‘installr’ is not available (for R version 3.2.1) 

Welcome to installr version 0.16.0

More information is available on the installr project website:
https://github.com/talgalili/installr/

Contact: <tal.galili@gmail.com>
Suggestions and bug-reports can be submitted at: https://github.com/talgalili/installr/issues

                        To suppress this message use:
                        suppressPackageStartupMessages(library(installr))

Warning message:
package ‘installr’ was built under R version 3.2.2 
>

**Comment by talgalili** [comment]
Hi @aruneral01 
It sounds like a CRAN/internet connection issue - and not an installr issue.
Please try changing your CRAN mirror.

Cheers,
Tal
