### ISSUE TITLE
Install older versions of R

### ISSUE THREAD

**Issue by talgalili** [talgalili/installr#42]
Maybe installr could grab from http://cran.r-project.org/bin/windows/base/old/

**Comment by suimong** [comment]
On a related subject, would you also consider checking updates of patched version? Perhaps add an switch argument to check.for.updates.R()?

**Comment by talgalili** [comment]
Does the function
install.Rdevel()
enough, or do you think there is a need for more?

**Comment by suimong** [comment]
I would say an additional install.Rpatched() would be nice. My argument is that the number of R users who could benefit from a less buggy, stable R (the patched version) would be larger than that of a new feature packed, but potentially more buggy R.

**Comment by talgalili** [comment]
I'm not available to add this at the time.
Please re-open if you want to discuss this further.
If someone wants to send a PR - I'll gladly review.
