### ISSUE TITLE
Error in file(con, "r") : cannot open the connection

### ISSUE THREAD

**Issue by moon-thestral** [talgalili/installr#43]
Using R 3.2.2 in Windows 8.1, I'm trying to import a qiime otu table file, using this code:

biom_otu_tax <- import_biom("D:/from_qiime/micro/results/otus_open_ref_R1otu_table_mc2_w_tax_no_pynast_failures.biom")

However, I get the error message:

Error in file(con, "r") : cannot open the connection

I have tried every combination of:
-First running setInternet2(TRUE) (this fixes it for most people)
-Setting my working directory to the file location
-Running it in R, rather than R Studio
-Opening R/R Studio as an administrator
-Restarting my computer

Nothing seems to fix it. Any advice?

**Comment by talgalili** [comment]
I don't know.
Please ask the maintainer of phyloseq:
Maintainer: Paul J. McMurdie <mcmurdie at alumni.stanford.edu>
