### ISSUE TITLE
updateR() Function

### ISSUE THREAD

**Issue by rizwanahmad** [talgalili/installr#44]
i am on R version 3.2.1 (2015-06-18) -- "World-Famous Astronaut"
Platform: i386-w64-mingw32/i386 (32-bit)
updateR() gives
Error in file(con, "r") : cannot open the connection
while rpackges are updated easily.why prolem for updateR().

**Comment by talgalili** [comment]
Please run
install.packages("installr")
to get the latest version and see if that works for you.

Tal
