### ISSUE TITLE
Error in updateR() : could not find function "setInternet2"

### ISSUE THREAD

**Issue by bbest** [talgalili/installr#45]
This package looks great! Would love to use this in a classroom setting, but am having trouble on a Mac. Since it was not available as a Mac binary (see [CRAN warning](https://www.r-project.org/nosvn/R.check/r-release-osx-x86_64-mavericks/installr-00check.html)) for the latest R version (3.2.3) using `install.packages("installr")`, I ran `devtools::install_github('talgalili/installr')` but then had this problem:

```r
installr::updateR()
```

```
Error in updateR() : could not find function "setInternet2"
```

Looking at the code for [updateR.R#L717-L720v](https://github.com/talgalili/installr/blame/1e6ecd38aa47656bad216d7d89ed7ec26ebb1934/R/updateR.R#L717-L720), I can understand how R is confused about whether `setInternet2` is a boolean value or a function:

```r
if(fast) { # set a bunch of parameters... (they are also better for blind people)
      # ...
      setInternet2 <- TRUE
   }
   
   if(setInternet2) setInternet2(TRUE) 
```

Is this `updateR()` function working for you in its current form?

Here's my session info...

```r
devtools::session_info()
```

```
Session info -----------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.2.3 (2015-12-10)
 system   x86_64, darwin13.4.0        
 ui       RStudio (0.99.841)          
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/Los_Angeles         
 date     2016-01-02                  

Packages ---------------------------------------------------------------------------------------------------------------------------
 package   * version date       source                             
 curl        0.9.3   2015-08-25 CRAN (R 3.2.0)                     
 devtools  * 1.9.1   2015-09-11 CRAN (R 3.2.0)                     
 digest      0.6.8   2014-12-31 CRAN (R 3.2.0)                     
 htmltools   0.2.6   2014-09-08 CRAN (R 3.2.0)                     
 httr        1.0.0   2015-06-25 CRAN (R 3.2.0)                     
 installr  * 0.17.1  2016-01-02 Github (talgalili/installr@d595a34)
 knitr       1.11    2015-08-14 CRAN (R 3.2.2)                     
 magrittr    1.5     2014-11-22 CRAN (R 3.2.0)                     
 memoise     0.2.1   2014-04-22 CRAN (R 3.2.0)                     
 R6          2.1.1   2015-08-19 CRAN (R 3.2.2)                     
 rmarkdown   0.8.1   2015-10-10 CRAN (R 3.2.2)                     
 stringi     1.0-1   2015-10-22 CRAN (R 3.2.0)                     
 stringr     1.0.0   2015-04-30 CRAN (R 3.2.0)                     
 yaml        2.1.13  2014-06-12 CRAN (R 3.2.0)
```

**Comment by talgalili** [comment]
Hi Ben,
Sadly, this only works for Windows. I have no idea how to upgrade R on a mac. If you wish to send information on it - I might be able to add it to some future release.

With regards,
Tal

**Comment by bbest** [comment]
whoah, that was a crazy fast response! ok, thanks very much. cheers!

**Comment by talgalili** [comment]
No worries :)

**Comment by w02222** [comment]
Hello, Mr. bbest, when I used the MAT model to reconstruct, a small error occurred in the R code, but the answer was not found. I hope to get your reply, thank you.
`MAT.T_ANN.h <- crossval(MAT.T_ANN, k=10, cv.method="h-block", h.dist=geo.dist, h.cutoff=300)
Error in crossval(MAT.T_ANN, k = 10, cv.method = "h-block", h.dist = geo.dist,  : 
  could not find function  crossval"` @bbest
