### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by dptriplett** [talgalili/installr#46]
Hello, Please see the following output and warning messages that appeared after using installr and let me know if you have any advice. Thanks!

> install.R()
trying URL 'http://cran.rstudio.com/bin/windows/base/R-3.2.3-win.exe'
Content type 'application/x-msdos-program' length 65380480 bytes (62.4 MB)
downloaded 62.4 MB

The file was downloaded succesfully into:
 C:\Users\DTRIPL~1\AppData\Local\Temp\RtmpWm4yM0/R-3.2.3-win.exe 

Running the installer now...

Installation status:  TRUE . Removing the file:
 C:\Users\DTRIPL~1\AppData\Local\Temp\RtmpWm4yM0/R-3.2.3-win.exe 
 (In the future, you may keep the file by setting keep_install_file=TRUE) 
Warning: files ‘Tcl/bin/tcl85.dll’, ‘Tcl/bin/tclpip85.dll’, ‘Tcl/bin/tclsh85.exe’, ‘Tcl/bin/tk85.dll’, ‘Tcl/bin/wish85.exe’, ‘Tcl/lib/Tktable/Tktable.dll’, ‘Tcl/lib/Tktable/pkgIndex.tcl’, ‘Tcl/lib/Tktable/tkTable.html’, ‘Tcl/lib/Tktable/tkTable.tcl’, ‘Tcl/lib/dde1.3/pkgIndex.tcl’, ‘Tcl/lib/dde1.3/tcldde13.dll’, ‘Tcl/lib/reg1.2/pkgIndex.tcl’, ‘Tcl/lib/reg1.2/tclreg12.dll’, ‘bin/i386/R.dll’, ‘bin/i386/R.exe’, ‘bin/i386/RSetReg.exe’, ‘bin/i386/Rblas.dll’, ‘bin/i386/Rcmd.exe’, ‘bin/i386/Rfe.exe’, ‘bin/i386/Rgraphapp.dll’, ‘bin/i386/Rgui.exe’, ‘bin/i386/Riconv.dll’, ‘bin/i386/Rlapack.dll’, ‘bin/i386/Rscript.exe’, ‘bin/i386/Rterm.exe’, ‘bin/i386/open.exe’, ‘etc/i386/Makeconf’, ‘library/KernSmooth/libs/i386/KernSmooth.dll’, ‘library/MASS/libs/i386/MASS.dll’, ‘library/Matrix/libs/i386/Matrix.dll’, ‘library/class/libs/i386/class.dll’, ‘library/cluster/libs/i386/cluster.dll’, ‘library/foreign/libs/i386/foreign.dll’, ‘library/grDevices/libs/i386/grDevices.dll’, ‘library/grDevices/libs/i386/winCairo.dll’, ‘library/graphics/libs/i386/graphics.dll’, ‘library/grid/libs/i386/grid.dll’, ‘library/lattice/libs/i386/lattice.dll’, ‘library/methods/libs/i386/methods.dll’, ‘library/mgcv/libs/i386/mgcv.dll’, ‘library/nlme/libs/i386/nlme.dll’, ‘library/nnet/libs/i386/nnet.dll’, ‘library/parallel/libs/i386/parallel.dll’, ‘library/rpart/libs/i386/rpart.dll’, ‘library/spatial/libs/i386/spatial.dll’, ‘library/splines/libs/i386/splines.dll’, ‘library/stats/libs/i386/stats.dll’, ‘library/survival/libs/i386/survival.dll’, ‘library/tcltk/libs/i386/tcltk.dll’, ‘library/tools/libs/i386/tools.dll’, ‘library/utils/libs/i386/utils.dll’, ‘modules/i386/internet.dll’, ‘modules/i386/lapack.dll’ are missing
[1] TRUE
Warning message:
In install.R() :
  There was some problem with installing R.  Some files are not what they should be (e.g: check MD5 sums did not pass all the tests). 
  You can try installing R again (either manually or through install.R()), 
  and if the problem persists you can file a bug report by running:  bug.report(package = 'installr') 
> bug.report(package = 'installr')
Package: installr
 Version: 0.17.0
 Maintainer: Tal Galili <tal.galili@gmail.com>
 Built: R 3.2.3; ; 2016-01-26 01:45:21 UTC; windows

R Version:
 platform = x86_64-w64-mingw32
 arch = x86_64
 os = mingw32
 system = x86_64, mingw32
 status = 
 major = 3
 minor = 2.1
 year = 2015
 month = 06
 day = 18
 svn rev = 68531
 language = R
 version.string = R version 3.2.1 (2015-06-18)
 nickname = World-Famous Astronaut

Windows 7 x64 (build 7601) Service Pack 1

Locale:
 LC_COLLATE=English_United States.1252;LC_CTYPE=English_United States.1252;LC_MONETARY=English_United States.1252;LC_NUMERIC=C;LC_TIME=English_United States.1252

Search Path:
 .GlobalEnv, package:installr, package:clusterPower, package:stats,
 package:graphics, package:grDevices, package:utils, package:datasets,
 package:methods, Autoloads, package:base

This package has a bug submission web page, which we will now attempt
to open.  The information above may be useful in your report. If the web
page doesn't work, you should send email to the maintainer,
Tal Galili <tal.galili@gmail.com>.
Error in shell.exec(url) : 
  file association for 'https://github.com/talgalili/installr/issues' not available or invalid

**Comment by talgalili** [comment]
Hi @dptriplett 
I changed updateR to no longer throw this error (in installr 0.17.2 - now on github)

With regards,
Tal
