### ISSUE TITLE
Fix install.CMake()

### ISSUE THREAD

**Issue by talgalili** [talgalili/installr#48]

**Comment by Tsteles** [comment]
I'm having some problems in update R with installr (Error in setInternet2(TRUE) : use != NA is defunct). How can I fix it? My Windows version is 10.

**Comment by talgalili** [comment]
Hi @Tsteles What R version are you currently using?

**Comment by Tsteles** [comment]
Oh, excuse me!!! My R version is the pre-release 3.3.0

**Comment by talgalili** [comment]
o.k., then
1) I don't think updateR will discover how to install 3.3.0 "post-release". So you'll just have to update it manually.
2) I'll install R 3.3.0 later and check if I can reproduce this error (if so - I'll gladly try to fix it).

Thanks,
Tal

**Comment by Tsteles** [comment]
Thanks Tal.
I'll try to do that and then write to you again.

Thiago.

**Comment by talgalili** [comment]
I installed R using installr, and it seems to have worked fine.
