### ISSUE TITLE
updateR does not pull latest version of R

### ISSUE THREAD

**Issue by joshua1zzard** [talgalili/installr#49]
When I try to update to R 3.2.4 the layout of the CRAN page has changed so latest_R_version comes back empty and I get the following error inside of check.for.updates.R(): 

Error in strsplit(version_with_dots, "\\.")[[1]] : 
  subscript out of bounds

**Comment by talgalili** [comment]
Thank you for the bug report @joshua1zzard  - this is due to the use of a new file name structure (i.e.:   "R-3.2.4revised-win.exe" ).
This is now resolved in installr 0.17.3.
I have now fixed it, and I'll send it to CRAN soon.
