### ISSUE TITLE
Error message: Error in strsplit(version_with_dots, "\\.")[[1]] :    subscript out of bounds

### ISSUE THREAD

**Issue by datamand** [talgalili/installr#50]
Hi there,

Like a few other, I encountered the following error message when running the updateR() command:
> updateR()
Error in strsplit(version_with_dots, "\\.")[[1]] : 
  subscript out of bounds

When I type R.home() I get this:
> R.home()
[1] "C:/PROGRA~1/R/R-31~1.2"

which looks weird!

However, when I go to the folder where R is installed, this is the path:
C:\Program Files\R\R-3.1.2

Thanks,
Anders

**Comment by talgalili** [comment]
Hi @datamand - 
I just pushed installr version 0.17.5 to github.
Please install it using:
```r
devtools::install_github('talgalili/installr')
```

And tell me if this resolves your issue.

Thanks.

**Comment by abeolson** [comment]
@talgalili : Not sure about @datamand , but updating to 0.17.5 this fixed the issue for me.

**Comment by talgalili** [comment]
Great, thanks for the report @abeolson

**Comment by datamand** [comment]
Hi all,
Sorry for the long response time. I was not able to install devtools package - I'm running Windows. Seems that my problem is not unique. In other words, I have not been able to update to 0.17.5... Will try again later. Thanks for working on the fix!
