### ISSUE TITLE
Compatibility error with R 3.2.X

### ISSUE THREAD

**Issue by soedr** [talgalili/installr#52]
Hey there,

I'm having issues installing `installr` in Rstudio v0.99.893, where I'm getting 

`package ‘installr’ is not available (for R version 3.2.4)` 

after I run `install.packages("installr")` (same issue occured on R v3.2.3)

Thanks for any help in advance!

**Comment by talgalili** [comment]
Hi Soedr,
1) Are you running on Windows?
2) Did you try changing the CRAN mirror you are using?

**Comment by soedr** [comment]
Hey Tal,

No, I'm running on OS X  - if that's the issue, then I apologize for a dumb
issue raise!

**Comment by talgalili** [comment]
installr is only for Windows, sorry...
