### ISSUE TITLE
Update R Issue-Unable update Latest version

### ISSUE THREAD

**Issue by nandhinik2** [talgalili/installr#54]
> updateR()
Error in strsplit(version_with_dots, "\\.")[[1]] : 
  subscript out of bounds

Thank you

**Comment by talgalili** [comment]
Hi all,
This issue should be now fixed (in installr 0.17.6)
You can install it using:

```r
if (!require('devtools')) install.packages('devtools'); # make sure you have Rtools installed first! if not, then run:
#install.packages('installr')
#install.Rtools()
devtools::install_github('talgalili/installr')
```

Please let me know if this solves your issue.

Best,
Tal

**Comment by nandhinik2** [comment]
Dear Sir,

Issue got resolved...

Thank you









*Thanks and Regards,Nandhini Krishnasamy,Ph.d Computer Science,Department
of Computer Science and Engineering,Bharathiar University,Coimbatore-46,
Tamilnadu.*

*"Research is to see what everybody else has seen, and to think what nobody
else has thought   ...Albert Szent-Gyorgyi"*

**Comment by talgalili** [comment]
Great :)
