### ISSUE TITLE
No packages to copy.  Goodbye :)

### ISSUE THREAD

**Issue by dannyjnwong** [talgalili/installr#58]
I'm updating my R installation from 3.2.4 to 3.3.0 and for some reason it installR doesn't transfer my packages across to the new installation. I keep getting the message "No packages to copy.  Goodbye :)"

I have tried to transfer the libraries across using `copy.packages.between.libraries(ask = T) ` but this has also been unsuccessful with the same message.

**Comment by dannyjnwong** [comment]
I realise the issue now, my user installed packages are in a different folder.

**Comment by talgalili** [comment]
Thanks for looking into this.

**Comment by giorjet** [comment]
hi Tal and danny,
I have the same problem (see [https://github.com/talgalili/installr/issues/66](url)
... but in my case the 2  libraries are in the same folder

could you help me?
many thanks
ps: installr version: 0.18.0
