### ISSUE TITLE
Error 127

### ISSUE THREAD

**Issue by jaiyow** [talgalili/installr#60]
The latest version R i.e 3.3.0 (70.2mb) was downloading but during installation returned a error 127 then the installr closed deleting the downloaded file and returning the error 127 message.

![ewg](https://cloud.githubusercontent.com/assets/4976366/15802196/46706ebe-2ac8-11e6-83c6-8a2e9b41ab47.JPG)

**Comment by talgalili** [comment]
What is your Windows / R versions?

**Comment by jaiyow** [comment]
R version 3.2.0 (2015-04-16)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7600)

locale:
[1] LC_COLLATE=English_India.1252  LC_CTYPE=English_India.1252    LC_MONETARY=English_India.1252
[4] LC_NUMERIC=C                   LC_TIME=English_India.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.2.0

**Comment by talgalili** [comment]
Which version of installr do you have installed?

**Comment by jaiyow** [comment]
installr version 0.17.8

**Comment by talgalili** [comment]
mmm, that is odd.
This should work fine (it does on my computer). Could it be that you have some permission issue?

**Comment by jaiyow** [comment]
Yes it was, the problem solved once i ran R as an administrator. Thanx for the help :)

**Comment by talgalili** [comment]
I'm glad it solved it.

Best,
Tal
