### ISSUE TITLE
use installr in Rstudio

### ISSUE THREAD

**Issue by frankcsliu** [talgalili/installr#63]
Hi, I love the idea of installr, but as a Rstudio user I really hope that this package runs smoothly in Rstudio without jump to the R terminal. 

Plus, I know this package is for Windows user so far, but I am look forward that this package could be extend to Mac users soon. Thank you! 

Sincerely, 
Frank

**Comment by talgalili** [comment]
Hi Frank,
Since I don't use mac I don't see myself developing this functionality.

As for working well with RStudio, I'll keep this issue open in order to look at it in the future.

With regards,
Tal

**Comment by talgalili** [comment]
Not sure how to followup on this. Closing. 
Please re-open if you want to discuss this further.
