### ISSUE TITLE
Copying of the package library :(

### ISSUE THREAD

**Issue by VMJim** [talgalili/installr#65]
Dear Tal,

It's me again :) writing about the old problem of copying the current library files to the new one. 

This went well for awhile... Until the latest update round (I update installr, close Rstudio, open the basic RGUI and run installr). Once again I had to manually copy the package library after installation. Then I noticed something. This was an R update from 3.2.\* to 3.3.1. When you look at the libraries that R keeps, you'll find that these are: 
- user\some\path\R\win-library\3.1
- user\some\path\R\win-library\3.2
- etc

So a possible cause for the bug is the updating from 3.2.\* to 3.3.\* (instead of: 3.2.1 to 3.2.2).  Maybe this helps. 

If not, please consider prompting the user of installr to explicitly indicate what his current library is and what his new library path should become.

Best,

Jim

**Comment by m-stanley** [comment]
I encountered the same issue when updating from 3.2.4(r) to 3.3.1. In fact I watched my /R/win-library/3.2 folder and installR was copying the packages... into the exact same folder. I could watch the modified dates being incremented on each folder in turn in the folder as they were moved. I still received the message in the terminal:

> No packages to copy. Goodbye :)

**Comment by janitabotha** [comment]
I think I have encountered the same problem when updating from R 3.5 to R 4.0

**Comment by talgalili** [comment]
Thanks everyone.
Since I no longer have a working Windows OS system, I won't be able to
easily debug this.
If anyone would like to debug it - please do - send a PR. And I'll gladly
review it.

T

**Comment by talgalili** [comment]
Not sure how to followup on this. Closing. 
Please re-open if you want to discuss this further.
