### ISSUE TITLE
problem copying  libraries

### ISSUE THREAD

**Issue by giorjet** [talgalili/installr#66]
hi Tal,
I used your great package many times (very usefull), but the last time (upgrading r from 3.25 to 3.31) it didn't copy the libraries from the old to the new version.

so I tried ...
`library("installr")X
copy.packages.between.libraries("C:/Users/utente/Documents/R/win-library/3.2", "C:/Users/utente/Documents/R/win-library/3.3", ask = FALSE, keep_old = TRUE, do_NOT_override_packages_in_new_R = TRUE)`

but the result is always : 

> No packages to copy.  Goodbye :)

could you help me?
many thanks
ps: installr version: 0.18.0

**Comment by giorjet** [comment]
hi Tal,
have you some idea about my problem?
thanks

**Comment by giorjet** [comment]
don't worry

when you can

giorgio

-- 

*/Giorgio /**/Nunia
/*
/*Direzione Ricerche Tote Next *//
//*Via IV Novembre, 19 - PADOVA*///*
*

ESOMAR Individual Membership Information 
<http://www.esomar.org/web/mmark/validation.php?id=217> 	***Tel: 0039 
049 8721062
Fax: 0039 049 8724542
Email: gnunia@totenext.it
Web: www.totenext.it*

/
This message contains confidential information intended only for the use 
of the addressee(s). If you are not the addressee, or the person 
responsible for delivering it to the addressee, you are hereby notified 
that reading, disseminating, distributing or copying this message is 
strictly prohibited. If you have received this message by mistake, 
please notify us, by replying to the sender, and delete the original 
message immediately thereafter. Thank you./

Il 27/10/2016 17:35, Tal Galili ha scritto:

**Comment by verty-1** [comment]
I have this same library update issue not encountered previously with installr:  "No packages to copy. Goodbye :)"
I'm attempting to update from R version 3.3.2 to 3.4.1 using the R gui.  Can you please fix.

**Comment by talgalili** [comment]
Not sure how to followup on this. Closing. 
Please re-open if you want to discuss this further.
