### ISSUE TITLE
version check on patched release?

### ISSUE THREAD

**Issue by mdsumner** [talgalili/installr#67]
Hi, the "need" to updateR() seems to check only the main release version number? 

Is there interest in having installr find and install the latest patched version?  

![patched](https://cloud.githubusercontent.com/assets/4107631/18454782/a9f3bd82-7989-11e6-824a-3c06248f8452.png)

**Comment by talgalili** [comment]
Hi,
Are you offering to add this feature?

**Comment by mdsumner** [comment]
Maybe :) I was just a bit surprised it's not already that way, I appreciate it's probably not easy

**Comment by talgalili** [comment]
It would probably require looking more into how we detect the latest
version of R, and also to check the patched version compared to it.
I admit I have little free time to venture there. But if you want to move
this forward, I'm open to pull requests :)

**Comment by talgalili** [comment]
Not sure how to followup on this. Closing. 
Please re-open if you want to discuss this further.

**Comment by mdsumner** [comment]
no worries, and  thanks - check out https://github.com/r-lib/rig that covers it all
