### ISSUE TITLE
Problem installing Pandoc

### ISSUE THREAD

**Issue by Jeet1994** [talgalili/installr#69]
Hello, 

I am trying to install Pandoc on R using installr. 

I am using installr 0.18.0 version. 

Whenever I do : 
`install.pandoc()`

I get the following error : 

```
Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") : InternetOpenUrl failed: '
```

I tried doing  `setInternet2()` but I get the following error in that case
`Error in setInternet2() : use != NA is defunct`

My sessionInfo() is : 

```
R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_India.1252  LC_CTYPE=English_India.1252   
[3] LC_MONETARY=English_India.1252 LC_NUMERIC=C                  
[5] LC_TIME=English_India.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] installr_0.18.0 knitr_1.14     

loaded via a namespace (and not attached):
[1] tools_3.3.1
```

Any help is appreciated.

**Comment by talgalili** [comment]
Hi @Jeet1994 
Thanks for the issue.

Please run the following line, what do you get?

`download.file('https://github.com/jgm/pandoc/releases/download/1.17.2/pandoc-1.17.2-windows.msi', "temp.msi")
`

**Comment by Jeet1994** [comment]
The RStudio aborts the R session when I try this

**Comment by talgalili** [comment]
This works fine for me from RGui and RStudio.
I can't seem to reproduce your reported error.
