### ISSUE TITLE
library with automatically installing pkgs

### ISSUE THREAD

**Issue by ChingChuan-Chen** [talgalili/installr#70]
I do not know whether this functionality fit in the purpose of installr.
I just hope there is a function can be used in automatic checking the packages we want to use.
And I think that adding this functionality is  to installr is proper.

A simple R code to fulfill:
``` R
library_chk <- function(..., lib.loc = NULL, quietly = FALSE, warn.conflicts = TRUE){
  pkgs <- setdiff(sapply(as.list(substitute(list(...))),as.character),"list")
  if (any(!pkgs %in% installed.packages()))
    install.packeges(pkgs[!pkgs %in% installed.packages()])
  invisible(sapply(pkgs, library, character.only = TRUE, lib.loc = lib.loc,
            quietly = quietly))
}
library_chk(ggplot2, devtools, installr)
```

**Comment by talgalili** [comment]
Hi @ChingChuan-Chen 
What do you think about the `require2` function already in the package?
(see line 1297 here: https://github.com/talgalili/installr/blob/8ade30b1e566d6ec03e1eac2757d5b06fe89900c/R/install.R )

**Comment by talgalili** [comment]
(although I am not sure if it is vectorizing or not - if not, you are welcome to send a pull request)

**Comment by ChingChuan-Chen** [comment]
I think that require2 meet my requirement. Thank you.

**Comment by talgalili** [comment]
:)
