### ISSUE TITLE
Microsoft R Open and R Studio

### ISSUE THREAD

**Issue by tshicelg** [talgalili/installr#73]
Hi Tal,

Great package!  Have been using it ever since it came out.

For the past year or so, I've switched over to Microsoft R.  Do you plan to add an option to your package to handle Microsoft R as some special features need to be considered, e.g. repository and their MKL package?

Also, I second other users' request.  It would be nice to integrate installr with Rstudio, so we can do upgrade within Rstudio with one click!

Thanks!

Tao

**Comment by talgalili** [comment]
Dear @tshicelg 
I currently don't think I'll get to adding these features, but they both sounds great.
If you'll get a chance to work on them - I'd be happy to add a pull request (especially for rstudio).
If not - it is also fine. I'll leave this issue open in the hopes someone else will get around to it.

Cheers,
Tal

**Comment by tshicelg** [comment]
Hi Tal,

Thanks for the quick reply!  Let's hope someone has some time for this, as I don't have the bandwidth either.

Best,

Tao

**Comment by Dripdrop12** [comment]
What do you guys think about creating some [RStudio-addins](https://rstudio.github.io/rstudioaddins/)? I'd be interested to help with that

**Comment by talgalili** [comment]
I have no experience in it. But if you'd like to create it, I'd happily
accept your pull request :)
