### ISSUE TITLE
Rprofile.site does not copy to new installation

### ISSUE THREAD

**Issue by mlaviolet** [talgalili/installr#74]
The last several times I ran updateR, I clicked yes on the prompt to copy Rprofile.site to the new installation, but found the standard file. The behavior occurs on both my office and personal systems. Please advise. Thanks!

**Comment by talgalili** [comment]
Thanks.
I can't debug this now, but please send me your sessionInfo()
Also, do you run R with admin privileges?

**Comment by mlaviolet** [comment]
A colleague ran updateR() under Rgui as administrator, but the Rprofile.site did not copy to the new install. Here's the sessionInfo. Thanks!

`R version 3.3.0 (2016-05-03)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252
[2] LC_CTYPE=English_United States.1252  
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                         
[5] LC_TIME=English_United States.1252   

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base 
 `

**Comment by talgalili** [comment]
Thanks @mlaviolet 
I won't get to fix this in the near future. If you or someone else will, I would be happy to accept the pull request.

Cheers,
Tal

**Comment by woodhaha** [comment]
Thanks@talgalili for your laborious works on developing R. 
I have upgraded to R3.4 using the pkg "installr", it works perfect on my win10 platfom.
