### ISSUE TITLE
Pass page_with_download_url from installR()

### ISSUE THREAD

**Issue by m1tca00** [talgalili/installr#75]
My site maintains a local cran mirror and generally blocks other internet traffic.  The check.for.updates.R() function includes a page_with_download_url option.  However, the installR() function never passes that option, so there's no way to use any alternate cran mirrors.

**Comment by talgalili** [comment]
> Interesting issue. 
Would you like to try and make a pull request on this?
(If not - I'll have a look at it)

**Comment by m1tca00** [comment]
Sure.

**Comment by talgalili** [comment]
Thanks @m1tca00 I accepted your pull request.
