### ISSUE TITLE
Error in file(con, "r")

### ISSUE THREAD

**Issue by chanksa** [talgalili/installr#77]
HI,
despite I tried > setInternet2(TRUE), 
function > if(!require("installr")) install.packages('installr') is still not running and 
giving back
 in file(con, "r") : for https:// URLs use setInternet2(TRUE)
Any ideas what to do?
Thanks

**Comment by talgalili** [comment]
What is your sessionInfo() output?

**Comment by GMD886** [comment]
Hi, 
I am also having this issue.  I setInternet2(TRUE) and it still gives the same error back: Error in file(con, "r") : for https:// URLs use setInternet2(TRUE)

**Comment by GMD886** [comment]
I am also having this problem after setInternet2(TRUE), it still gives the same error back:
-----------------------------------
> library(installr)

Welcome to installr version 0.19.0

More information is available on the installr project website:
https://github.com/talgalili/installr/

Contact: <tal.galili@gmail.com>
Suggestions and bug-reports can be submitted at: https://github.com/talgalili/installr/issues

                        To suppress this message use:
                        suppressPackageStartupMessages(library(installr))

> setInternet2(TRUE)
> updateR()
Error in file(con, "r") : for https:// URLs use setInternet2(TRUE)
--------------------------------------------------------------------------

**Comment by talgalili** [comment]
Not sure how to followup on this. Closing. 
Please re-open if you want to discuss this further.
