### ISSUE TITLE
character.only option for require2

### ISSUE THREAD

**Issue by ChingChuan-Chen** [talgalili/installr#79]
If I have multiple packages to library and I want to use a variable to store the names of packages.

With `library`, I can do it in following way, not with `require2`.
Ex:
``` R
usedPkgs <- c("data.table", "plyr", "stringr")
sapply(usedPkgs, library, character.only = TRUE)
```

Could `require2` add a option for ` character.only`?
Or I can get the same effect without `character.only` option?

The modification is as following:
``` R
require2 <- function (package, ask = FALSE, character.only = FALSE, ...) 
{
    if (!character.only)
        package <- as.character(substitute(package))
    if (!suppressWarnings(require(package = package, character.only = TRUE))) {
        if (ask) {
            install_package <- ask.user.yn.question(paste("Package ", 
                package, " is not installed. Do you want to install it now?"))
        }
        else {
            install_package <- TRUE
        }
        if (install_package) 
            install.packages(pkgs = package)
    }
    require(package = package, character.only = TRUE)
}
```

**Comment by talgalili** [comment]
Could you please make the changes here:
https://github.com/talgalili/installr/blob/master/R/install.R
(line 1303)
Submit a pull request, and I'll review it?

Thanks!

**Comment by talgalili** [comment]
Code merged.
