### ISSUE TITLE
Error message on new R installation

### ISSUE THREAD

**Issue by PPGHPP** [talgalili/installr#81]
Could you please tell what does the message below mean?
"Installation status:  TRUE . Removing the file:
 C:\Users\...\AppData\Local\Temp\RtmpS6N7y6/R-3.3.2-win.exe
 (In the future, you may keep the file by setting keep_install_file=TRUE)

We can not seem to find the location if the new R you have installed.
The rest of the updating process is aborted, please take care to copy
your packages to the new R installation.
[1] TRUE
Warning message:
In setInternet2(TRUE) : internet routines were already initialized"

**Comment by talgalili** [comment]
This should have been fixed in the more recent version of installr. Which version do you currently have installed?

**Comment by PPGHPP** [comment]
Thank you for the answer.
I have currently R-3.1.1 installed.
I'll be trying the new installr soon.

2017-02-05 20:25 GMT+02:00 Tal Galili <notifications@github.com>:

**Comment by PPGHPP** [comment]
Hi again,
I updated R, and got the same error message as before, but the installation
went OK.

2017-02-05 21:04 GMT+02:00 Pirkko Pietiläinen <pirkkoptlnn@gmail.com>:
