### ISSUE TITLE
installr on Ubuntu

### ISSUE THREAD

**Issue by X-OneTwo-X** [talgalili/installr#88]
My current version of R on Ubuntu is the R version 3.2.5 (2016-04-14). I'd like to update it with the package installr but it doesn't work. Could you help me to solve this problem please ?

Thank you,
Valentin.

**Comment by AndreaCirilloAC** [comment]
installR package is for windows OS only. you can find the equivalent for Unix on UpdateR package: https://github.com/AndreaCirilloAC/updateR
cheers

**Comment by talgalili** [comment]
Not sure how to followup on this. Closing. 
Please re-open if you want to discuss this further.
