### ISSUE TITLE
MikTex 64-bit fails to download

### ISSUE THREAD

**Issue by JohnBeal** [talgalili/installr#89]
Using installr 0.17.5 MikTex 64-bit fails to download giving the following error message:

Note: I also experienced timeout errors when downloading MikTex from mirror sites using the net installer from Miktex.org (2.9.6300-x64).

installr()
============= Which version of MiKTeX do you want? ====================
  version
1      32
2      64
Please review the table of versions from above,
and enter the row number of the file-version you'd like to install: 2

Explanation of the error: You didn't enter a valid .EXE URL. 
This is likely to have happened because there was a change in the software download page, and the function you just ran no longer works. 

 This is often caused by a change in the URL of the installer file in the download page of the software (making our function unable to know what to download). 

 Please e-mail: tal.galili@gmail.com and let me know this function needs updating/fixing - thanks!

We failed to download the file into:
 C:\Users\J84C6~1.BEA\AppData\Local\Temp\RtmpIJORg5/http: 
(i.e.: the installation failed)

sessionInfo():

R version 3.1.2 (2014-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=English_New Zealand.1252  LC_CTYPE=English_New Zealand.1252    LC_MONETARY=English_New Zealand.1252
[4] LC_NUMERIC=C                         LC_TIME=English_New Zealand.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] installr_0.17.5

loaded via a namespace (and not attached):
[1] tools_3.1.2

**Comment by talgalili** [comment]
You are using a very old version of installr (0.17.5), please update to the latest (0.19.0) vis: `install.packages("installr")`. This bug was fixed (AFIK) at version 0.18.1.

Cheers,
Tal

**Comment by JohnBeal** [comment]
Thanks, Tal.

After updating R and R Studio I was able to update installr and install Miktex.
My apologies, I should have tried that first. I hadn't released my version of
installr was old because I had just installed it.

Cheers,

John

Quoting Tal Galili <notifications@github.com>:

**Comment by talgalili** [comment]
> All is good. Cheers. 
Tal
