### ISSUE TITLE
update R-devel based on SVN build

### ISSUE THREAD

**Issue by jackwasey** [talgalili/installr#90]
Thanks for this useful package.

I tried to update R-devel from a few months ago, and was told that I was already on the most recent version. I assume this is because the SVN version string is not checked.

**Comment by talgalili** [comment]
> Hi there
Thanks. 
What code did you run?

**Comment by jackwasey** [comment]
```
installr::updateR()
```

I was running the current CRAN version in a December 2016 R-devel installation.

I also looked for a force option which might be useful for any version re-installation, but didn't see one: did I miss it?

**Comment by talgalili** [comment]
You can use
install.R()
But will then need to copy the packages. 
I think updateR has a check parameter that when is set to FALSE should install without checking. Could you check it?

**Comment by jackwasey** [comment]
I just reviewed the parameters in current github and the CRAN installed version, and didn't see such a flag.

BTW I also noticed your code didn't use the official function to [compare R versions](https://stat.ethz.ch/R-manual/R-devel/library/utils/html/compareVersion.html) but that may well be deliberate, and wouldn't help in the R-devel case anyway.

R seems to offer `R.version.string` which contains the date, but not the SVN release. Might be useful.

**Comment by talgalili** [comment]
Hi Jack,

First, I think the way to go about this is to use the following commands:

```r
library(installr)
install.R()
copy.packages.between.libraries(ask=TRUE)
```

Regarding `compareVersion`, that is interesting. I am not sure at which version of R this function was added - but it might be worth moving to use it in the future. 

Please reopen the issue if the above did not help.

Tal
