### ISSUE TITLE
Fix install.GraphicsMagick()

### ISSUE THREAD

**Issue by talgalili** [talgalili/installr#93]

**Comment by dariomasante** [comment]
I second this, plus install.ImageMagick() needs a fix too, the correct URL now is
https://www.imagemagick.org/script/download.php

**Comment by mister-walter** [comment]
To install ImageMagick before this is fixed in installr, you can use this:
```
install.imagemagick(URL="https://www.imagemagick.org/script/download.php")
```

**Comment by talgalili** [comment]
Thanks, this is fixed in the version on github:
```
if (!require('devtools')) install.packages('devtools'); # make sure you have Rtools installed first! if not, then run:
#install.packages('installr')
#install.Rtools()
devtools::install_github('talgalili/installr')
```

I'll hopefully get it to CRAN in the next couple of weeks.
