### ISSUE TITLE
Error in file(con, "r") : for https:// URLs use setInternet2(TRUE)

### ISSUE THREAD

**Issue by zhangyudoc** [talgalili/installr#94]
> library(installr)
> updateR()
Error in file(con, "r") : for https:// URLs use setInternet2(TRUE)
> 
Please help me!

**Comment by talgalili** [comment]
What is your
sessionInfo()
?

**Comment by 546492928** [comment]
@talgalili 
R-3.1.3 on windows8.1 x64

> install.packages("installr")
Warning in install.packages :
  cannot open: HTTP status was '404 Not Found'
Warning in install.packages :
  cannot open: HTTP status was '404 Not Found'
Warning in install.packages :
  unable to access index for repository http://dmlc.github.io/drat/bin/windows/contrib/3.1
Installing package into ‘C:/Users/turbo1/Documents/R/win-library/3.1’
(as ‘lib’ is unspecified)
Warning in install.packages :
  cannot open: HTTP status was '404 Not Found'
Warning in install.packages :
  cannot open: HTTP status was '404 Not Found'
Warning in install.packages :
  unable to access index for repository http://dmlc.github.io/drat/bin/windows/contrib/3.1

  有二进制版本（将被安装），但源代码版本是后来的:
         binary source
installr 0.17.5 0.19.0

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.1/installr_0.17.5.zip'
Content type 'application/zip' length 244334 bytes (238 KB)
opened URL
downloaded 238 KB

package ‘installr’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\turbo1\AppData\Local\Temp\RtmpwxXEZe\downloaded_packages
> library(installr)

Welcome to installr version 0.17.5

More information is available on the installr project website:
https://github.com/talgalili/installr/

Contact: <tal.galili@gmail.com>
Suggestions and bug-reports can be submitted at: https://github.com/talgalili/installr/issues

			To suppress this message use:
			suppressPackageStartupMessages(library(installr))

> updateR()
Error in file(con, "r") : for https:// URLs use setInternet2(TRUE)
>

**Comment by 546492928** [comment]
@talgalili 

> sessionInfo()
R version 3.1.3 (2015-03-09)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8 x64 (build 9200)

locale:
[1] LC_COLLATE=Chinese (Simplified)_China.936  LC_CTYPE=Chinese (Simplified)_China.936   
[3] LC_MONETARY=Chinese (Simplified)_China.936 LC_NUMERIC=C                              
[5] LC_TIME=Chinese (Simplified)_China.936    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] installr_0.17.5

loaded via a namespace (and not attached):
[1] tools_3.1.3
>

**Comment by JNvV01** [comment]
> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] desctable_0.1.0

loaded via a namespace (and not attached):
 [1] compiler_3.4.1   magrittr_1.5     assertthat_0.2.0 R6_2.2.2         tools_3.4.1      bindrcpp_0.2     glue_1.1.1      
 [8] dplyr_0.7.3      tibble_1.3.4     Rcpp_0.12.12     pkgconfig_2.0.1  rlang_0.1.2      bindr_0.1       
> 

same problem of Error in file(con, "r") even after installing version from GitHub & updating R & RStudio to latest versions.

No insight into how to solve the problem but just indicating the issue seems prevalent

**Comment by philipkab** [comment]
Hello @talgalili,
I am going through the same issue. I have the lastest version of R 3.4.2. Working through Rstudio interface. I got the error message:
Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") :
  cannot open file 'C:\weather_data\5051_1999_1.csv': No such file or directory

I have tried couple of things such as :+1: 
install.packages('installr')
then 
if (!require('devtools')) install.packages('devtools'); # make sure you have Rtools installed first! if not, then run:
#install.packages('installr')
#install.Rtools()
devtools::install_github('talgalili/installr')

While trying to run setInternet2(TRUE), I got this:
Error: 'setInternet2' is defunct.
See help("Defunct")

Do you have an idea about how to fix this issue?

Thank you very much,

**Comment by lkockel** [comment]
Hello,
I am facing the same problem. I run:
R version 3.1.3 (2015-03-09)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 7 (build 7601) Service Pack 1

 If I run updateR(setInternet2 = TRUE) 

or 

> setInternet2(TRUE)
> updateR()

I get: Error in file(con, "r") : for https:// URLs use setInternet2(TRUE)

Please help. Thank you

**Comment by yasodajayaweera** [comment]
Hello,
I'm facing the same issue.

**Steps followed:**

> > library(installr)
> 
> Welcome to installr version 0.17.5
> 
> More information is available on the installr project website:
> https://github.com/talgalili/installr/
> 
> Contact: <tal.galili@gmail.com>
> Suggestions and bug-reports can be submitted at: https://github.com/talgalili/installr/issues
> 
> 			To suppress this message use:
> 			suppressPackageStartupMessages(library(installr))
> 
> > setInternet2(TRUE)
> > updateR()
> Error in file(con, "r") : for https:// URLs use setInternet2(TRUE)

**Session infor:**

> > sessionInfo()
> R version 3.1.3 (2015-03-09)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 7 x64 (build 7601) Service Pack 1
> 
> locale:
> [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
> [3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
> [5] LC_TIME=English_United States.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] installr_0.17.5
> 
> loaded via a namespace (and not attached):
> [1] tools_3.1.3

Please help. Thank you.

**Comment by talgalili** [comment]
Not sure how to followup on this. Closing. 
Please re-open if you want to discuss this further.
