### ISSUE TITLE
Using installr with Microsoft Azure ML Studio

### ISSUE THREAD

**Issue by Mahak-8** [talgalili/installr#95]
I am using Microsoft Azure ML studio to build an API for stream clustering. For this, I am using stream package in R. I installed stream package taking reference from - https://blogs.msdn.microsoft.com/benjguin/2014/09/24/how-to-upload-an-r-package-to-azure-machine-learning/

But the dependency "proxy" generates following error -
[Critical]     Error: Error 0063: The following error occurred during evaluation of R script:
---------- Start of error message from R ----------
This is R 3.1.0, package 'proxy' needs >= 3.3.2

So I tried to update the version of R in Azure ML studio by installing installr package following the same procedure as mentioned above. It gave the following warnings and errors  -

[ModuleOutput] Warning messages:
[ModuleOutput] 
[ModuleOutput] 1: In strptime(x, format, tz = tz) :
[ModuleOutput] 
[ModuleOutput]   unable to identify current timezone 'C':
[ModuleOutput] 
[ModuleOutput] please set environment variable 'TZ'
[ModuleOutput] 
[ModuleOutput] 2: In strptime(x, format, tz = tz) : unknown timezone 'localtime'
[ModuleOutput] 
[ModuleOutput] 3: package 'stringr' was built under R version 3.4.0 
[ModuleOutput] 
[ModuleOutput] 4: package 'installr' was built under R version 3.4.0 
[ModuleOutput] 
[ModuleOutput] 5: In get.installed.R.folders() :
[ModuleOutput] 
[ModuleOutput]   Could not find any R installation on your system. (You might have installed your R version on 'c:\R' without sub folders...
[ModuleOutput] 
[ModuleOutput] 6: In file(con, "r") :
[ModuleOutput] 
[ModuleOutput]   InternetOpenUrl failed: 'The certificate authority is invalid or incorrect'
[ModuleOutput] 
[ModuleOutput] End R Execution: 6/27/2017 5:20:29 AM
[Stop]     DllModuleMethod::Execute. Duration = 00:00:17.6445528
[Critical]     Error: Error 0063: The following error occurred during evaluation of R script:
---------- Start of error message from R ----------
cannot open the connection

cannot open the connection
----------- End of error message from R -----------

Please help!

**Comment by talgalili** [comment]
Hi,
I don't see why you need to use installr for your work.
What is the link to the package that requires installr?

**Comment by Mahak-8** [comment]
Hi,

The dependency "proxy" of stream package requires R version >= 3.3.2

[Critical] Error: Error 0063: The following error occurred during evaluation of R script:
 ---------- Start of error message from R ----------
 This is R 3.1.0, package 'proxy' needs >= 3.3.2

**Comment by talgalili** [comment]
Could you send me a link to this package? (on CRAN I don't see any other
package depending on installr other the RInno)

**Comment by Mahak-8** [comment]
No, the package "proxy" is not required by installr, it is required for stream package that I want to use.
Link - https://cran.r-project.org/web/packages/proxy/index.html

In my script, import statements after the installations - 
library(proxy, lib.loc=".", verbose=TRUE)
library(stream, lib.loc=".", verbose=TRUE)

If I do not import proxy then it generates following error - 

[Critical]     Error: Error 0063: The following error occurred during evaluation of R script:
---------- Start of error message from R ----------
package 'proxy' required by 'stream' could not be found

package 'proxy' required by 'stream' could not be found
----------- End of error message from R -----------

**Comment by talgalili** [comment]
So how is this related to installr??

**Comment by Mahak-8** [comment]
I am using installr to update the installed R version (3.1.0) to latest version in Azure ML Studio.

Do you know what these errors mean or are they related to installr?
InternetOpenUrl failed: 'The certificate authority is invalid or incorrect'

**Comment by talgalili** [comment]
Not sure how to followup on this. Closing. 
Please re-open if you want to discuss this further.
